TOFU_QA_forget:
  handler: QADataset
  args:
    hf_args:
      path: json
      data_files: /home/research/research/reproduction/06-correlated-recovery/data/explicit_correlated_v1.json
      split: train
    question_key: question
    answer_key: answer
    max_length: 512
