# @package eval.tofu

defaults:
  - tofu_metrics:
    - heldout_Q_A_Prob
    - heldout_Q_A_ROUGE

handler: TOFUEvaluator
batch_size: 1
output_dir: ${paths.output_dir}
metrics: {}
overwrite: true

forget_split: forget01
holdout_split: holdout10
retain_logs_path: null
question_key: question
