import type { GuidedLessonSeed } from "../guidedLessonTypes";

export const reductionLessonBlueprints: GuidedLessonSeed[] = [
  {
    id: 201,
    title: "Sum Reduction",
    intuition: "很多线程先各自搬一小份并求局部和，再像淘汰赛一样两两合并，最后只留下整个数组的总和。",
    formula: "S=\\sum_{i=0}^{N-1}x_i",
    symbols: [
      { symbol: "x_i", meaning: "输入数组的第 i 个元素" },
      { symbol: "N", meaning: "参与求和的元素总数" },
      { symbol: "S", meaning: "所有输入元素的最终总和" },
    ],
    flow: [
      "线程分段读取并累加局部和",
      "局部和写入 shared memory",
      "所有线程先执行 __syncthreads()，再第一次读取其他线程的局部和",
      "用连续活跃线程和无冲突索引折半合并；stride 大于 warp 宽度时，每轮结束后所有线程执行 __syncthreads()",
      "只剩一个 warp 后用带有效掩码的 __shfl_down_sync 完成尾归约，lane 0 得到 block 和",
      "各 block 向全局内存写出部分和",
      "当前 kernel 结束形成全局边界；后续 kernel 递归归约部分和，直到输出唯一的 S",
    ],
    flowIds: [
      "read-registers",
      "write-shared",
      "block-barrier",
      "shared-tree-reduce",
      "warp-tail",
      "write-block-sum",
      "finalize-grid-sum",
    ],
    misconception: "一次 block 内的 __syncthreads() 不能同步整个 grid；多 block 的部分和必须由新 kernel、协作组或受控原子操作继续合并。",
    debugTip: "用 8 个连续整数逐轮保存 shared memory：首轮局部值、每次 stride 后的有效槽位以及每个 block 部分和都应与 CPU 分段求和一致；再用 profiler 检查 shared bank conflict。",
    takeaway: "求和归约靠分层合并把全局问题缩成 block 部分和，并在每次共享数据被复用前正确同步。",
  },
  {
    id: 202,
    title: "Max / Min Reduction",
    intuition: "每个线程先找自己负责片段里的极值，再在 warp、block 和 grid 三层逐级比较，最终留下全局最大值或最小值。",
    formula: "\\left(m_{\\min},m_{\\max}\\right)=\\left(\\min_{0\\le i<N}x_i,\\max_{0\\le i<N}x_i\\right)",
    symbols: [
      { symbol: "x_i", meaning: "输入数组的第 i 个候选值" },
      { symbol: "m_{\\min}", meaning: "全局最小值" },
      { symbol: "m_{\\max}", meaning: "全局最大值" },
      { symbol: "N", meaning: "候选元素数量" },
    ],
    flow: [
      "先拒绝或预处理 NaN/Inf；本课只对有限浮点数定义极值归约",
      "线程从全局内存读取多个候选值",
      "寄存器中形成线程局部极值",
      "warp shuffle 逐级交换并比较",
      "每个 warp 的 lane 0 把极值对写入 shared memory，所有线程执行 __syncthreads()",
      "第一个 warp 读取各 warp 的有效结果，并再次用 shuffle 合成 block 极值对",
      "归约 kernel 1 把每个 block 的最小值/最大值对写入全局部分量数组",
      "kernel 1 结束形成跨 block 边界；若部分量多于一对，就继续启动归约 kernel",
      "最后一个归约 kernel 把唯一的最小值/最大值对写到输出",
    ],
    misconception: "最大值归约不能用 0 作为通用初值；全为负数时会得到错误答案。本课明确拒绝非有限输入，避免不同指令对 NaN 产生不一致结果。",
    debugTip: "以 [-7,-2,-9,-4] 测最大值，逐 lane 查看 shuffle 前后的候选值，block 输出必须是 -2；再检查尾部越界线程使用的哨兵值，并确认 NaN/Inf 在 kernel 启动前被拒绝。",
    takeaway: "极值归约与求和共享分层结构，但初始哨兵和非有限输入策略必须在接口边界明确。",
  },
  {
    id: 203,
    title: "L2 Norm",
    intuition: "先找出全局最大绝对值作为尺子，把每个分量缩小后再平方求和，最后乘回尺度；这样能避免大数在平方阶段提前溢出。",
    formula: "s=\\max_i|x_i|,\\qquad \\lVert x\\rVert_2=\\begin{cases}0,&s=0,\\\\s\\sqrt{\\sum_{i=0}^{N-1}(x_i/s)^2},&s>0.\\end{cases}",
    symbols: [
      { symbol: "x_i", meaning: "向量的第 i 个分量" },
      { symbol: "s", meaning: "全局最大绝对值，用来把分量缩放到安全范围" },
      { symbol: "(x_i/s)^2", meaning: "缩放后不易溢出的平方贡献" },
      { symbol: "\\lVert x\\rVert_2", meaning: "向量的欧几里得范数" },
    ],
    flow: [
      "最大值 kernel 合并读取 x_i，并在寄存器计算局部 |x_i| 最大值",
      "warp 结果写入 shared memory，__syncthreads() 后合成 block 最大值并写出部分量",
      "kernel 结束形成全局边界；递归归约部分量，得到全局尺度 s",
      "若 s=0 直接写出 0；否则启动平方和 kernel，重新读取 x_i 并累加 (x_i/s)^2",
      "平方和 kernel 的 warp 结果写入 shared memory，__syncthreads() 后合成 block 的 q 部分量并写出",
      "kernel 结束形成全局边界；递归归约 q 部分量，得到全局 q",
      "最终 kernel 的一个线程计算 s*sqrt(q) 并写回范数",
    ],
    misconception: "L2 Norm 不是先对每个元素开方再求和；直接计算 x_i^2 可能在最终范数仍可表示时提前溢出，块内屏障也不能代替两个全局归约之间的 kernel 边界。",
    debugTip: "用 [3,4] 应看到 s=4、缩放平方和 q=1.5625、最终范数 5；再用 [3e20,4e20] 检查结果约为 5e20，且 s、q 和输出都不是 Inf 或 NaN。",
    takeaway: "稳定 L2 Norm 先求全局尺度，再归约缩放平方和，最后跨 kernel 合成为 s*sqrt(q)。",
  },
];
