import type { GuidedLessonSeed } from "../guidedLessonTypes";

export const stencilConvLessonBlueprints: GuidedLessonSeed[] = [
  {
    id: 501,
    title: "Conv2d",
    intuition: "卷积核像一扇小窗口按步幅滑动；相邻输出窗口高度重叠，因此线程块把中心区域和 halo 一起缓存。把每个窗口展平来看，它又正是 Im2Col 或不落盘的 Implicit GEMM。",
    formula: "Y_{n,k,p,q}=\\sum_{c=0}^{C-1}\\sum_{r=0}^{R-1}\\sum_{s=0}^{S-1}\\widetilde X_{n,c,pu+r-P_h,qv+s-P_w}W_{k,c,r,s}",
    symbols: [
      { symbol: "\\widetilde X", meaning: "带零 padding 的输入；原图范围外的值按 0 处理" },
      { symbol: "W_{k,c,r,s}", meaning: "输出通道 k 对应的卷积核权重" },
      { symbol: "Y_{n,k,p,q}", meaning: "输出特征图在位置 (p,q) 的值" },
      { symbol: "R\\times S", meaning: "卷积核的空间尺寸" },
      { symbol: "u,v", meaning: "垂直和水平方向的 stride" },
      { symbol: "P_h,P_w", meaning: "垂直和水平方向的 padding" },
    ],
    flow: [
      "把输出位置 (n,p,q) 看作矩阵行，把 (c,r,s) 展平成归约维；显式存窗口就是 Im2Col，不落盘取数就是 Implicit GEMM",
      "线程块映射一块输出特征图，并按 pu+r-P_h、qv+s-P_w 计算输入坐标",
      "线程从全局内存合并加载有效输入 tile、halo 与权重，padding 范围补 0",
      "块内同步后展开当前通道 tile 的窗口乘加",
      "所有线程再次同步，确认 shared tile 读完后再切换通道 tile",
      "累加器写回对应输出元素",
    ],
    misconception: "公式不能把 stride 永远当 1、padding 永远当 0；Im2Col 也只是显式物化窗口，Implicit GEMM 用相同映射即时取数，不能遗漏 halo 或边界补零。",
    debugTip: "用单通道 3x3 输入、2x2 核先测 stride=1、padding=0，再测 stride=2、padding=1；打印映射坐标、补零位置和每个 r,s 的乘积，与 CPU 窗口逐项核对。",
    takeaway: "Conv2d 用统一的窗口到 GEMM 映射处理 stride/padding，再选择 Im2Col 落盘或 Implicit GEMM 的 shared-tile 复用。",
  },
  {
    id: 502,
    title: "MaxPool2d",
    intuition: "每个输出位置只保留对应滑动窗口里的最大值，像从每小块特征图中挑出最强响应。",
    formula: "Y_{n,c,p,q}=\\max_{0\\le r<R,\\,0\\le s<S}X_{n,c,pu+r,qv+s}\\quad\\text{(valid pooling, no padding)}",
    symbols: [
      { symbol: "X_{n,c,pu+r,qv+s}", meaning: "步幅为 (u,v) 时池化窗口内的输入" },
      { symbol: "R\\times S", meaning: "池化窗口的高和宽" },
      { symbol: "Y_{n,c,p,q}", meaning: "窗口最大值形成的输出元素" },
      { symbol: "u,v", meaning: "垂直和水平方向的步幅" },
    ],
    flow: [
      "线程映射一个输出窗口",
      "线程按窗口地址从全局内存读取输入",
      "线程内比较全部候选，无需块内同步",
      "边界检查后写回最大值输出",
    ],
    misconception: "本式采用无 padding 的 valid pooling；池化窗口不是固定等于输出 tile，步幅也不一定等于窗口大小，索引算错会让相邻线程读取错误区域。",
    debugTip: "对 4x4 输入逐线程打印窗口左上角、读取的 R*S 个值和 running max；2x2、stride=2 时四个窗口必须与 CPU 切片完全相同。",
    takeaway: "MaxPool2d 通常是一线程一窗口，性能取决于窗口索引正确性和对非连续读取的有效组织。",
  },
  {
    id: 503,
    title: "Gaussian Blur",
    intuition: "每个像素用周围邻居做加权平均，越近权重越大；二维高斯还能拆成先横向、再纵向的两次一维滤波。",
    formula: "\\widetilde X_{p,q}=X_{\\operatorname{clip}(p,0,H_{img}-1),\\operatorname{clip}(q,0,W_{img}-1)},\\qquad H_{p,q}=\\sum_{s=-R}^{R}g_s\\widetilde X_{p,q+s},\\qquad Y_{p,q}=\\sum_{r=-R}^{R}g_rH_{\\operatorname{clip}(p+r,0,H_{img}-1),q},\\qquad G_{r,s}=g_rg_s",
    symbols: [
      { symbol: "X_{p+r,q+s}", meaning: "输出像素周围的输入邻居" },
      { symbol: "G_{r,s}", meaning: "二维高斯核在偏移 (r,s) 处的权重" },
      { symbol: "g_r", meaning: "可分离的一维高斯权重" },
      { symbol: "\\widetilde X", meaning: "采用 clamp-to-edge 边界规则扩展后的输入图像" },
      { symbol: "H_{img},W_{img}", meaning: "输入图像的高度和宽度" },
      { symbol: "H_{p,q}", meaning: "横向 kernel 写入全局临时缓冲的中间结果" },
      { symbol: "Y_{p,q}", meaning: "模糊后的输出像素" },
    ],
    flow: [
      "横向 kernel 从全局输入协作加载像素 tile；越界的左右 halo 用最近边缘像素填充",
      "从 constant memory 广播一维权重；__syncthreads() 后执行横向卷积",
      "横向线程把结果写入独立的全局临时缓冲 H[p,q]",
      "横向 kernel 结束形成全局边界，保证 H 全部可见后再启动纵向 kernel",
      "纵向 kernel 从全局 H 重新加载 tile；越界的上下 halo 同样 clamp 到最近边缘",
      "所有线程执行 __syncthreads() 后读取完整 tile，做纵向卷积并写回 Y",
    ],
    misconception: "可分离卷积只在核满足 G=g g^T 时成立；两遍处理还必须使用独立临时缓冲，不能让未完成的结果覆盖输入。",
    debugTip: "先检查一维权重和接近 1，再分别对中心脉冲与角落脉冲打印横向临时行和纵向输出；中心图案应等于 g 的外积，角落结果应符合 clamp-to-edge 且不能越界读取。",
    takeaway: "高斯模糊用 constant memory 保存小核、shared memory 复用 halo，并以两次一维卷积减少计算量。",
  },
];
