import type { GuidedLessonSeed } from "../guidedLessonTypes";

export const elementWiseLessonBlueprints: GuidedLessonSeed[] = [
  {
    id: 102,
    title: "Scale (ax + b)",
    intuition: "把每个输入元素看成流水线上的一件物品：线程各取一件，先按 a 缩放，再统一加上偏置 b，彼此完全不用等待。",
    formula: "y_i=a x_i+b,\\qquad 0\\le i<N",
    symbols: [
      { symbol: "x_i", meaning: "输入向量中下标 i 的元素" },
      { symbol: "y_i", meaning: "线程 i 计算出的输出元素" },
      { symbol: "a", meaning: "作用于所有元素的缩放因子" },
      { symbol: "b", meaning: "作用于所有元素的偏置" },
    ],
    flow: [
      "线程计算全局下标 i",
      "线程从全局内存合并读取 x_i",
      "独立执行乘加，无需同步",
      "合并写回输出 y_i",
    ],
    misconception: "a 和 b 是所有线程共享的标量参数，不需要为每个元素各存一份；真正的大流量来自输入和输出数组。",
    debugTip: "先用 N=3、a=2、b=1 检查每个线程的 i 和中间乘积 a*x_i，应依次为 2、4、6，再核对输出 3、5、7。",
    takeaway: "一线程一元素配合连续读写，就能把 ax+b 映射成简单而高吞吐的 CUDA 核函数。",
  },
  {
    id: 103,
    title: "ReLU / LeakyReLU",
    intuition: "每个线程像一道独立闸门：正数原样通过，负数在 ReLU 中被截为零，在 LeakyReLU 中只保留一小段斜率。",
    formula: "y_i=\\max(x_i,0)+\\alpha\\min(x_i,0)",
    symbols: [
      { symbol: "x_i", meaning: "第 i 个待激活的输入" },
      { symbol: "y_i", meaning: "第 i 个激活结果" },
      { symbol: "\\alpha", meaning: "负半轴斜率；取 0 时就是 ReLU" },
    ],
    flow: [
      "线程绑定一个元素 i",
      "线程从全局内存连续读取 x_i",
      "用 max/min 选通分支，无需同步",
      "连续写回激活输出 y_i",
    ],
    misconception: "GPU 上出现条件并不一定严重变慢；这里可用 max/min 表达，关键是避免同一 warp 内复杂且耗时不同的分支路径。",
    debugTip: "用输入 [-2,0,3] 和 alpha=0.1，逐线程记录 min(x_i,0) 与 max(x_i,0)，应得到输出 [-0.2,0,3]；alpha=0 时首项应变为 0。",
    takeaway: "ReLU 系列是无数据依赖的逐元素门控，连续访存通常比算术本身更决定性能。",
  },
  {
    id: 104,
    title: "Sigmoid / Tanh",
    intuition: "每个线程把一个实数压进有限区间：Sigmoid 压到 0 和 1 之间，Tanh 压到 -1 和 1 之间，指数运算是主要成本。",
    formula: "\\sigma(x_i)=\\frac{1}{1+e^{-x_i}},\\qquad \\tanh(x_i)=\\frac{e^{x_i}-e^{-x_i}}{e^{x_i}+e^{-x_i}}",
    symbols: [
      { symbol: "x_i", meaning: "第 i 个输入值" },
      { symbol: "\\sigma(x_i)", meaning: "第 i 个输入的 Sigmoid 值" },
      { symbol: "\\tanh(x_i)", meaning: "第 i 个输入的双曲正切值" },
      { symbol: "e", meaning: "自然常数，也是指数函数的底" },
    ],
    flow: [
      "线程定位输入元素 i",
      "线程从全局内存合并读取 x_i",
      "调用指数或快速数学指令，无需同步",
      "将选定激活输出写回 y_i",
    ],
    misconception: "用低精度或快速近似并非总是等价；当 |x| 很大时，直接展开指数还可能溢出或损失有效精度。",
    debugTip: "分别检查两种函数：Sigmoid(0)=0.5 且输出应落在 (0,1)；Tanh(0)=0、输出应落在 [-1,1]，并满足 Tanh(-x)=-Tanh(x)。再用 x=-10、10 确认结果有限。",
    takeaway: "Sigmoid 与 Tanh 仍是一线程一元素，但要同时观察特殊函数吞吐和极端输入的数值稳定性。",
  },
  {
    id: 105,
    title: "Cast (FP32 -> FP16)",
    intuition: "类型转换像把大盒子里的数重新装进小盒子：数值尽量保留，但位数减少会带来舍入、溢出或下溢。",
    formula: "y_i=\\operatorname{round}_{\\mathrm{FP16}}(x_i)",
    symbols: [
      { symbol: "x_i", meaning: "以 FP32 保存的第 i 个输入" },
      { symbol: "y_i", meaning: "舍入后以 FP16 保存的第 i 个输出" },
      { symbol: "\\operatorname{round}_{\\mathrm{FP16}}", meaning: "按 FP16 可表示集合执行的舍入" },
    ],
    flow: [
      "线程按向量宽度领取连续元素",
      "从全局内存向量化读取 FP32 数据",
      "逐 lane 转换，无需线程同步",
      "对齐写回紧凑的 FP16 输出；不足一个向量宽度的尾部用边界掩码或标量路径处理",
    ],
    misconception: "内存占用减半不代表所有数值都不变；FP16 的有效位和指数范围更小，转换本身可能改变结果。",
    debugTip: "同时记录转换前后的位模式与绝对误差；至少检查 1.0、0.1、65504 和一个很小的数，并用长度 5 验证向量宽度为 4 时尾元素不会漏写或越界。",
    takeaway: "高效 Cast 既要让读写对齐并向量化，也要明确接受 FP32 到 FP16 的表示误差。",
  },
  {
    id: 106,
    title: "Dropout",
    intuition: "每个线程用种子和自己的编号抽一张可复现的签：抽中就保留输入并放大，未抽中就写零，从而保持训练时的期望值。",
    formula: "m_i=\\mathbf{1}[u_i\\ge p],\\qquad y_i=\\frac{m_i x_i}{1-p}",
    symbols: [
      { symbol: "u_i", meaning: "线程 i 由计数器随机数生成器得到的均匀随机数" },
      { symbol: "p", meaning: "元素被丢弃的概率，满足 0<=p<1" },
      { symbol: "m_i", meaning: "取 0 或 1 的保留掩码" },
      { symbol: "y_i", meaning: "采用 inverted dropout 缩放后的输出" },
    ],
    flow: [
      "线程用全局下标构造 Philox 计数器",
      "从全局内存读取 x_i 并生成 u_i",
      "独立生成掩码，无需线程同步",
      "写回掩码与缩放后的输出 y_i",
    ],
    misconception: "仅把元素置零却不除以 1-p，会让训练期输出均值变小；不同线程复用同一随机状态还会制造相关掩码。",
    debugTip: "固定 seed 后打印前 8 个线程的 counter、u_i 和 m_i，重复运行必须一致；例如 X=[1,1,1,1]、p=0.5、掩码 [1,0,0,1] 时，inverted dropout 输出必须是 [2,0,0,2]，再用大样本检查丢弃比例接近 p。",
    takeaway: "Dropout 的核心不只是置零，还包括每线程独立且可复现的随机状态以及正确的期望缩放。",
  },
];
