import type { GuidedLessonSeed } from "../guidedLessonTypes";

export const scanSortLessonBlueprints: GuidedLessonSeed[] = [
  {
    id: 301,
    title: "Inclusive Scan",
    intuition: "输出的每个位置都要知道自己以及左边所有输入之和；GPU 让线程分轮交换越来越远的部分和，而不是让一个线程从头累加。",
    formula: "y_i=\\sum_{j=0}^{i}x_j",
    symbols: [
      { symbol: "x_j", meaning: "输入数组第 j 个元素" },
      { symbol: "y_i", meaning: "包含 x_i 在内的第 i 个前缀和" },
      { symbol: "i", meaning: "当前输出位置" },
    ],
    flow: [
      "线程把连续元素载入两份 shared memory 缓冲中的当前缓冲",
      "所有线程先执行 __syncthreads()，再开始读取距离 1 的邻居",
      "按 1、2、4 的距离从当前缓冲读、向备用缓冲写，每轮 __syncthreads() 后交换两份缓冲",
      "各 block 向全局内存写出局部前缀与块总和",
      "当前 kernel 结束；新 kernel 扫描块总和并形成每个 block 的全局偏移",
      "偏移 kernel 结束；回填 kernel 给局部前缀加偏移并写回全局输出",
    ],
    misconception: "只完成每个 block 内的 scan 并不等于全局 scan；后续 block 必须加上所有前置 block 的总和。",
    debugTip: "对 [1,2,3,4,5] 记录每轮 shared memory、每块总和和块偏移；局部结果加偏移后必须严格得到 [1,3,6,10,15]。",
    takeaway: "全局 Inclusive Scan 由块内同步扫描、块总和扫描和偏移回填三个层次组成。",
  },
  {
    id: 302,
    title: "Radix Sort",
    intuition: "本课固定处理 uint32 非负键：每一轮只看关键字的一小段位，把相同数字稳定地放在一起；从低位到高位重复后，完整关键字自然有序。",
    formula: "d_i=(k_i\\gg r)\\mathbin{\\&}1,\\quad \\rho_i=\\sum_{j=b(i)T}^{i-1}\\mathbf 1[d_j=d_i],\\quad \\operatorname{pos}_i=B_{d_i}+O_{b(i),d_i}+\\rho_i",
    symbols: [
      { symbol: "k_i", meaning: "第 i 个待排序 uint32 非负关键字" },
      { symbol: "r", meaning: "当前处理的二进制位位置" },
      { symbol: "d_i", meaning: "关键字在第 r 位上的 0 或 1" },
      { symbol: "B_{d_i}", meaning: "数字 0 或 1 在全局输出中的起始位置" },
      { symbol: "O_{b(i),d_i}", meaning: "当前 block 之前、同数字元素的总数" },
      { symbol: "\\rho_i", meaning: "当前 block 内、i 之前同数字元素的稳定局部 rank" },
      { symbol: "T", meaning: "每个 block 本轮处理的元素数" },
      { symbol: "k^{(r)}", meaning: "完成前 r 个低位轮次后的序列" },
    ],
    flow: [
      "校验输入为 uint32 非负键；计数/rank kernel 读取当前缓冲，提取 d_i，并在 shared memory 写入 isZero_i 与 isOne_i",
      "全 block 同步后，对两组 0/1 标志做双缓冲 exclusive scan；每一轮只读当前缓冲、写备用缓冲，再 __syncthreads() 后交换",
      "线程从对应数字的 scan 结果取得稳定局部 rank rho_i，将它写入全局 localRank[i]；同步后由指定线程把两组末值与末标志相加，写出 blockHist[b,0/1]",
      "计数/rank kernel 结束形成全局边界；一个或分层多个 scan kernel 按 block 顺序扫描 blockHist",
      "scan 结果给出 O_{b,d}，并由全局 0 总数得到 B_0=0、B_1=total_0",
      "scan kernel 结束形成全局边界；scatter kernel 读取 localRank[i]，用 B_d+O_{b,d}+rho_i 计算唯一位置",
      "线程稳定写入备用缓冲；scatter kernel 结束后交换缓冲，再处理下一位",
    ],
    misconception: "rho_i 不能用竞争式原子递增随意编号：LSD radix sort 要求同一数字保持输入相对顺序。register/shared 数据也不能跨 kernel 保留，因此局部 rank 必须写入全局缓冲供 scatter 读取。",
    debugTip: "用 [3,1,4,2] 打印每一位的 isZero/isOne、每轮 exclusive-scan 缓冲、global localRank、blockHist、O 与 pos；再给相等 key 附原始序号，确认顺序不变且每个 pos 只写一次。",
    takeaway: "Radix Sort 用位提取、计数扫描和稳定重排，把全局排序拆成一连串规则的并行内存操作。",
  },
  {
    id: 303,
    title: "Histogram",
    intuition: "每个线程读取样本并给对应桶投一票；先在 block 内建立小直方图，再合并到全局，可以减少所有线程争抢同一计数器。",
    formula: "h_b=\\sum_{i=0}^{N-1}\\mathbf{1}\\!\\left[q(x_i)=b\\right]",
    symbols: [
      { symbol: "x_i", meaning: "线程 i 处理的输入样本" },
      { symbol: "q(x_i)", meaning: "把样本映射到桶编号的函数" },
      { symbol: "b", meaning: "当前统计的桶编号" },
      { symbol: "h_b", meaning: "落入桶 b 的样本数量" },
    ],
    flow: [
      "在同一 stream 先用 cudaMemsetAsync 或 clear kernel 把全局输出桶全部置 0",
      "清零操作完成后启动统计 kernel，线程协作清零本 block 的 shared memory 桶",
      "块内同步后从全局内存合并读取输入样本",
      "对共享桶执行 atomicAdd",
      "再次同步确认块直方图完成",
      "线程把块计数原子合并到全局内存输出",
    ],
    misconception: "普通的 hist[bin]++ 不是线程安全操作；shared 桶仍需原子更新，而全局桶若未在统计 kernel 前清零，还会把本轮结果错误地累加到旧数据上。",
    debugTip: "先把全局桶填成非零哨兵，再执行清零与统计；对 [1,1,2,3] 使用 4 个桶，最终必须是 [0,2,1,1]，总和为 4，重复运行也不能残留上次计数。",
    takeaway: "高效直方图通过 block 私有化降低全局原子争用，同时用两次同步保护共享桶的初始化与合并。",
  },
];
