import type { CudaStoryboardDefinition } from "./storyboard.ts";

export const scanSortSceneDefinitions: Record<number, CudaStoryboardDefinition> = {
  301: {
    kind: "array",
    ariaLabel: "五个整数在双缓冲 shared memory 中完成 inclusive scan",
    entities: [
      { id: "input", label: "输入 x", role: "input", initialValue: [1, 2, 3, 4, 5] },
      { id: "buffer-a", label: "shared 当前缓冲", role: "intermediate", initialValue: [0, 0, 0, 0, 0] },
      { id: "barrier", label: "块内屏障", role: "control", initialValue: "waiting" },
      { id: "buffer-b", label: "shared 备用缓冲", role: "intermediate", initialValue: [0, 0, 0, 0, 0] },
      { id: "round-offset-1", label: "距离 1 后缓冲", role: "intermediate", initialValue: [0, 0, 0, 0, 0] },
      { id: "round-offset-2", label: "距离 2 后缓冲", role: "intermediate", initialValue: [0, 0, 0, 0, 0] },
      { id: "round-offset-4", label: "距离 4 后缓冲", role: "intermediate", initialValue: [0, 0, 0, 0, 0] },
      { id: "local-prefix", label: "block 局部前缀", role: "intermediate", initialValue: [0, 0, 0, 0, 0] },
      { id: "block-total", label: "block 总和", role: "intermediate", initialValue: 0 },
      { id: "block-offset", label: "全局 block 偏移", role: "intermediate", initialValue: "pending" },
      { id: "output", label: "全局前缀 y", role: "output", initialValue: [0, 0, 0, 0, 0] },
    ],
    formulaEntityIds: [["input", "buffer-a"], ["output"], ["local-prefix", "output"]],
    layout: {
      orientation: "horizontal",
      groups: [
        { id: "global-input", label: "全局输入", entityIds: ["input"] },
        {
          id: "double-buffer",
          label: "shared 双缓冲与轮次",
          entityIds: ["buffer-a", "barrier", "round-offset-1", "round-offset-2", "round-offset-4", "buffer-b"],
        },
        { id: "block-results", label: "block 结果", entityIds: ["local-prefix", "block-total"] },
        { id: "global-fixup", label: "跨 block 回填", entityIds: ["block-offset", "output"] },
      ],
    },
    steps: [
      {
        title: "连续输入载入当前缓冲",
        sourceEntityIds: ["input"],
        targetEntityIds: ["buffer-a"],
        values: { "buffer-a": [1, 2, 3, 4, 5] },
        result: "buffer A = [1, 2, 3, 4, 5]",
        explanation: "线程按下标把输入放进 shared 当前缓冲，备用缓冲暂不读取。",
      },
      {
        title: "首个屏障释放距离 1 读取",
        sourceEntityIds: ["buffer-a"],
        targetEntityIds: ["barrier"],
        values: { barrier: "released for offset 1" },
        result: "所有 x_i 已可被左侧邻居读取",
        explanation: "屏障保证距离 1 的每个读取都看到完整的上一轮数组。",
      },
      {
        title: "按距离 1、2、4 交换缓冲",
        sourceEntityIds: ["buffer-a", "barrier"],
        targetEntityIds: ["round-offset-1", "round-offset-2", "round-offset-4", "buffer-b", "local-prefix"],
        values: {
          "round-offset-1": [1, 3, 5, 7, 9],
          "round-offset-2": [1, 3, 6, 10, 14],
          "round-offset-4": [1, 3, 6, 10, 15],
          "buffer-b": [1, 3, 6, 10, 15],
          "local-prefix": [1, 3, 6, 10, 15],
        },
        inputEntityIds: ["buffer-a", "barrier"],
        outputEntityIds: ["round-offset-1", "round-offset-2", "round-offset-4", "buffer-b", "local-prefix"],
        transfers: [
          { from: "buffer-a", to: "round-offset-1", payload: [1, 2, 3, 4, 5], label: "距离 1 读取初始缓冲" },
          { from: "barrier", to: "round-offset-1", payload: "released for offset 1", label: "屏障放行第一次邻居读取" },
          { from: "round-offset-1", to: "round-offset-2", payload: [1, 3, 5, 7, 9], label: "屏障后交换缓冲并读取距离 2" },
          { from: "round-offset-2", to: "round-offset-4", payload: [1, 3, 6, 10, 14], label: "屏障后交换缓冲并读取距离 4" },
          { from: "round-offset-4", to: "buffer-b", payload: [1, 3, 6, 10, 15], label: "最终轮成为当前缓冲" },
          { from: "round-offset-4", to: "local-prefix", payload: [1, 3, 6, 10, 15], label: "发布 block 局部前缀" },
        ],
        result: "轮次 [1,3,5,7,9] -> [1,3,6,10,14] -> [1,3,6,10,15]",
        explanation: "每轮只读当前缓冲并写备用缓冲，屏障后再交换角色，避免同轮读写竞争。",
      },
      {
        title: "写出局部前缀和 block 总和",
        sourceEntityIds: ["local-prefix"],
        targetEntityIds: ["block-total"],
        values: { "block-total": 15 },
        inputEntityIds: ["local-prefix"],
        outputEntityIds: ["local-prefix", "block-total"],
        result: "局部前缀 [1,3,6,10,15]，block 总和 15",
        explanation: "最后一个有效槽位同时成为供下一层扫描使用的 block 总和。",
      },
      {
        title: "新 kernel 扫描 block 总和",
        sourceEntityIds: ["block-total"],
        targetEntityIds: ["block-offset"],
        values: { "block-offset": 0 },
        transfers: [{ from: "block-total", to: "block-offset", payload: 15, label: "第一个 block 前没有前置总和" }],
        result: "block 0 的全局偏移 = 0",
        explanation: "本例只有一个 block；多 block 时这里会得到所有前置 block 的总和。",
      },
      {
        title: "回填偏移得到全局前缀",
        sourceEntityIds: ["local-prefix", "block-offset"],
        targetEntityIds: ["output"],
        values: { output: [1, 3, 6, 10, 15] },
        expression: "y_i=local_i+offset_b",
        result: "y = [1, 3, 6, 10, 15]",
        explanation: "局部前缀逐项加上 block 偏移，形成完整的全局 inclusive scan。",
      },
    ],
  },
  302: {
    kind: "pipeline",
    ariaLabel: "四个 uint32 键提取最低位并稳定散射的 radix sort 轮次",
    entities: [
      { id: "keys", label: "当前键 k", role: "input", initialValue: [3, 1, 4, 2] },
      { id: "bit-index", label: "首轮位 r", role: "control", initialValue: 0 },
      { id: "remaining-bits", label: "后续有效位", role: "control", initialValue: [1, 2] },
      { id: "block-size", label: "每 block 元素数 T", role: "control", initialValue: 4 },
      { id: "digits", label: "最低位 d", role: "intermediate", initialValue: [0, 0, 0, 0] },
      { id: "flags", label: "isZero / isOne", role: "intermediate", initialValue: "pending" },
      { id: "ranks", label: "稳定局部 rank", role: "intermediate", initialValue: [0, 0, 0, 0] },
      { id: "histogram", label: "blockHist [0,1]", role: "intermediate", initialValue: [0, 0] },
      { id: "offsets", label: "数字起点 B+O", role: "intermediate", initialValue: [0, 0] },
      { id: "positions", label: "唯一输出位置", role: "intermediate", initialValue: [0, 0, 0, 0] },
      { id: "buffer", label: "备用键缓冲", role: "output", initialValue: [0, 0, 0, 0] },
      { id: "bit-1-digits", label: "bit 1 digits", role: "intermediate", initialValue: [0, 0, 0, 0] },
      { id: "bit-1-ranks", label: "bit 1 stable ranks", role: "intermediate", initialValue: [0, 0, 0, 0] },
      { id: "bit-1-positions", label: "bit 1 positions", role: "intermediate", initialValue: [0, 0, 0, 0] },
      { id: "bit-1-buffer", label: "bit 1 scatter buffer", role: "intermediate", initialValue: [0, 0, 0, 0] },
      { id: "bit-2-digits", label: "bit 2 digits", role: "intermediate", initialValue: [0, 0, 0, 0] },
      { id: "bit-2-ranks", label: "bit 2 stable ranks", role: "intermediate", initialValue: [0, 0, 0, 0] },
      { id: "bit-2-positions", label: "bit 2 positions", role: "intermediate", initialValue: [0, 0, 0, 0] },
      { id: "bit-2-buffer", label: "bit 2 最终有序缓冲", role: "output", initialValue: [0, 0, 0, 0] },
    ],
    formulaEntityIds: [
      ["keys"], ["bit-index", "remaining-bits"], ["digits"], ["offsets"],
      ["offsets"], ["ranks"], ["block-size"], ["buffer", "bit-1-buffer", "bit-2-buffer"],
    ],
    layout: {
      laneIds: ["计数/rank kernel", "全局扫描", "scatter kernel"],
      laneByEntityId: {
        keys: "计数/rank kernel",
        "bit-index": "计数/rank kernel",
        "remaining-bits": "计数/rank kernel",
        "block-size": "计数/rank kernel",
        digits: "计数/rank kernel",
        flags: "计数/rank kernel",
        ranks: "计数/rank kernel",
        histogram: "全局扫描",
        offsets: "全局扫描",
        positions: "scatter kernel",
        buffer: "scatter kernel",
        "bit-1-digits": "计数/rank kernel",
        "bit-1-ranks": "计数/rank kernel",
        "bit-1-positions": "scatter kernel",
        "bit-1-buffer": "scatter kernel",
        "bit-2-digits": "计数/rank kernel",
        "bit-2-ranks": "计数/rank kernel",
        "bit-2-positions": "scatter kernel",
        "bit-2-buffer": "scatter kernel",
      },
      stageEntityIds: [
        "keys", "bit-index", "remaining-bits", "block-size", "digits", "flags", "ranks", "histogram", "offsets", "positions", "buffer",
        "bit-1-digits", "bit-1-ranks", "bit-1-positions", "bit-1-buffer",
        "bit-2-digits", "bit-2-ranks", "bit-2-positions", "bit-2-buffer",
      ],
    },
    steps: [
      {
        title: "提取 bit 0 并写 0/1 标志",
        sourceEntityIds: ["keys", "bit-index"],
        targetEntityIds: ["digits", "flags"],
        values: { digits: [1, 1, 0, 0], flags: ["0/1", "0/1", "1/0", "1/0"] },
        outputEntityIds: ["digits", "flags"],
        transfers: [
          { from: "keys", to: "digits", payload: [3, 1, 4, 2], label: "读取四个 uint32 键" },
          { from: "bit-index", to: "digits", payload: 0, label: "提取 bit 0" },
          { from: "digits", to: "flags", payload: [1, 1, 0, 0], label: "每个 digit 写出 0/1 双标志" },
        ],
        result: "d = [1, 1, 0, 0]",
        explanation: "uint32 键 3、1 为奇数，4、2 为偶数；两组标志进入 shared 双缓冲。",
      },
      {
        title: "exclusive scan 两组标志",
        sourceEntityIds: ["flags"],
        targetEntityIds: ["ranks"],
        values: { ranks: [0, 1, 0, 1] },
        result: "同数字稳定 rank = [0, 1, 0, 1]",
        explanation: "每项只统计它之前相同数字的数量，因此相等数字保留输入次序。",
      },
      {
        title: "发布 localRank 与 blockHist",
        sourceEntityIds: ["ranks", "digits"],
        targetEntityIds: ["histogram"],
        values: { histogram: [2, 2] },
        inputEntityIds: ["ranks", "digits"],
        outputEntityIds: ["ranks", "histogram"],
        result: "blockHist = [2 zeros, 2 ones]",
        explanation: "局部 rank 写到全局缓冲，末值加末标志得到本 block 的两个计数。",
      },
      {
        title: "kernel 边界后扫描 blockHist",
        sourceEntityIds: ["histogram"],
        targetEntityIds: ["offsets"],
        values: { offsets: [0, 2] },
        result: "B_0 = 0，B_1 = 2",
        explanation: "全局零元素总数为 2，所以所有 bit-1 键从输出位置 2 开始。",
      },
      {
        title: "组合全局数字起点与 block 偏移",
        sourceEntityIds: ["digits", "ranks", "offsets"],
        targetEntityIds: ["positions"],
        values: { positions: [2, 3, 0, 1] },
        transfers: [
          { from: "digits", to: "positions", payload: [1, 1, 0, 0], label: "digit 选择全局 0/1 分区" },
          { from: "ranks", to: "positions", payload: [0, 1, 0, 1], label: "稳定 rank 保留同 digit 输入次序" },
          { from: "offsets", to: "positions", payload: [0, 2], label: "数字起点定位两个全局分区" },
        ],
        expression: "pos_i=B_d+O_{b,d}+\\rho_i",
        result: "pos = [2, 3, 0, 1]",
        explanation: "每个输入键现在有唯一位置，且同一 digit 内的位置按稳定 rank 递增。",
      },
      {
        title: "scatter kernel 读取持久化 rank",
        sourceEntityIds: ["keys", "ranks", "positions"],
        targetEntityIds: ["buffer"],
        values: { buffer: [4, 2, 3, 1] },
        result: "bit 0 稳定散射 = [4, 2, 3, 1]",
        explanation: "局部 rank 来自全局缓冲，因为寄存器和 shared 数据不能跨 kernel 保存。",
      },
      {
        title: "交换缓冲并完成 bit 1 与 bit 2",
        sourceEntityIds: ["buffer", "remaining-bits"],
        targetEntityIds: [
          "bit-1-digits", "bit-1-ranks", "bit-1-positions", "bit-1-buffer",
          "bit-2-digits", "bit-2-ranks", "bit-2-positions", "bit-2-buffer", "keys",
        ],
        values: {
          "bit-1-digits": [0, 1, 1, 0],
          "bit-1-ranks": [0, 0, 1, 1],
          "bit-1-positions": [0, 2, 3, 1],
          "bit-1-buffer": [4, 1, 2, 3],
          "bit-2-digits": [1, 0, 0, 0],
          "bit-2-ranks": [0, 0, 1, 2],
          "bit-2-positions": [3, 0, 1, 2],
          "bit-2-buffer": [1, 2, 3, 4],
          keys: [1, 2, 3, 4],
        },
        inputEntityIds: ["buffer", "remaining-bits"],
        outputEntityIds: [
          "bit-1-digits", "bit-1-ranks", "bit-1-positions", "bit-1-buffer",
          "bit-2-digits", "bit-2-ranks", "bit-2-positions", "bit-2-buffer", "keys",
        ],
        transfers: [
          { from: "buffer", to: "bit-1-digits", payload: [4, 2, 3, 1], label: "读取 bit 0 散射结果" },
          { from: "remaining-bits", to: "bit-1-digits", payload: [1, 2], label: "依次处理后续有效位 1 和 2" },
          { from: "bit-1-digits", to: "bit-1-ranks", payload: [0, 1, 1, 0], label: "bit 1 按数字做稳定 rank" },
          { from: "bit-1-ranks", to: "bit-1-positions", payload: [0, 0, 1, 1], label: "bit 1 rank 组合全局起点" },
          { from: "buffer", to: "bit-1-buffer", payload: [4, 2, 3, 1], label: "bit 1 scatter 读取当前键" },
          { from: "bit-1-positions", to: "bit-1-buffer", payload: [0, 2, 3, 1], label: "bit 1 scatter 按唯一位置写入" },
          { from: "bit-1-buffer", to: "bit-2-digits", payload: [4, 1, 2, 3], label: "交换缓冲并读取 bit 2" },
          { from: "bit-2-digits", to: "bit-2-ranks", payload: [1, 0, 0, 0], label: "bit 2 按数字做稳定 rank" },
          { from: "bit-2-ranks", to: "bit-2-positions", payload: [0, 0, 1, 2], label: "bit 2 rank 组合全局起点" },
          { from: "bit-1-buffer", to: "bit-2-buffer", payload: [4, 1, 2, 3], label: "bit 2 scatter 读取当前键" },
          { from: "bit-2-positions", to: "bit-2-buffer", payload: [3, 0, 1, 2], label: "bit 2 scatter 按唯一位置写入" },
          { from: "bit-2-buffer", to: "keys", payload: [1, 2, 3, 4], label: "交换缓冲并发布最终有序键" },
        ],
        result: "bit 1 得到 [4,1,2,3]；bit 2 得到有序缓冲 [1,2,3,4]",
        explanation: "样例最大键为 4，完成 bit 2 后更高位全为零，继续稳定轮次不会再改变顺序。",
      },
    ],
  },
  303: {
    kind: "array",
    ariaLabel: "样本一一二三先统计 shared 桶再合并到全局直方图",
    entities: [
      { id: "samples", label: "输入样本 x", role: "input", initialValue: [1, 1, 2, 3] },
      { id: "global-bins-before-clear", label: "清零前全局桶快照", role: "intermediate", initialValue: [9, 9, 9, 9] },
      { id: "global-bins-zero-base", label: "全局桶零基线", role: "intermediate", initialValue: "pending" },
      { id: "global-bins", label: "全局桶 h[0..3]", role: "output", initialValue: [9, 9, 9, 9] },
      { id: "shared-bins-before-clear", label: "清零前 shared 桶快照", role: "intermediate", initialValue: [9, 9, 9, 9] },
      { id: "shared-bins-zero-base", label: "shared 桶零基线", role: "intermediate", initialValue: "pending" },
      { id: "shared-bins", label: "block shared 桶", role: "intermediate", initialValue: [9, 9, 9, 9] },
      { id: "barrier-load", label: "初始化屏障", role: "control", initialValue: "waiting" },
      { id: "mapped-bins", label: "线程桶编号 q(x_i)", role: "intermediate", initialValue: [0, 0, 0, 0] },
      { id: "barrier-merge", label: "合并屏障", role: "control", initialValue: "waiting" },
      { id: "sample-count", label: "计数总和", role: "intermediate", initialValue: 0 },
    ],
    formulaEntityIds: [["samples"], ["mapped-bins"], ["shared-bins", "global-bins"], ["global-bins"]],
    layout: {
      orientation: "horizontal",
      groups: [
        { id: "input", label: "输入", entityIds: ["samples", "mapped-bins"] },
        { id: "shared", label: "block 私有直方图", entityIds: ["shared-bins-before-clear", "shared-bins-zero-base", "shared-bins", "barrier-load", "barrier-merge"] },
        { id: "global", label: "全局结果", entityIds: ["global-bins-before-clear", "global-bins-zero-base", "global-bins", "sample-count"] },
      ],
    },
    steps: [
      {
        title: "先清零全局输出桶",
        sourceEntityIds: ["global-bins-before-clear"],
        targetEntityIds: ["global-bins-zero-base", "global-bins"],
        values: {
          "global-bins-zero-base": [0, 0, 0, 0],
          "global-bins": [0, 0, 0, 0],
        },
        transfers: [
          { from: "global-bins-before-clear", to: "global-bins-zero-base", payload: [9, 9, 9, 9], label: "保留本轮全局原子加的零基线" },
          { from: "global-bins-before-clear", to: "global-bins", payload: [9, 9, 9, 9], label: "清零 kernel 覆盖旧哨兵值" },
        ],
        result: "旧哨兵 [9,9,9,9] 被清为 [0,0,0,0]",
        explanation: "独立清零操作先完成，避免把本轮计数错误叠加到旧结果。",
      },
      {
        title: "线程协作清零 shared 桶",
        sourceEntityIds: ["shared-bins-before-clear"],
        targetEntityIds: ["shared-bins-zero-base", "shared-bins"],
        values: {
          "shared-bins-zero-base": [0, 0, 0, 0],
          "shared-bins": [0, 0, 0, 0],
        },
        transfers: [
          { from: "shared-bins-before-clear", to: "shared-bins-zero-base", payload: [9, 9, 9, 9], label: "保留本轮 shared 原子加的零基线" },
          { from: "shared-bins-before-clear", to: "shared-bins", payload: [9, 9, 9, 9], label: "线程覆盖旧 shared 哨兵值" },
        ],
        result: "shared bins = [0, 0, 0, 0]",
        explanation: "block 内线程分工初始化私有桶，为低争用统计做好准备。",
      },
      {
        title: "屏障后读取并映射样本",
        sourceEntityIds: ["shared-bins", "samples"],
        targetEntityIds: ["barrier-load", "mapped-bins"],
        values: { "barrier-load": "released", "mapped-bins": [1, 1, 2, 3] },
        outputEntityIds: ["mapped-bins", "barrier-load"],
        transfers: [
          { from: "shared-bins", to: "barrier-load", payload: [0, 0, 0, 0], label: "shared 桶初始化完成" },
          { from: "samples", to: "mapped-bins", payload: [1, 1, 2, 3], label: "样本映射为桶编号" },
        ],
        result: "q(x) = [1, 1, 2, 3]",
        explanation: "只有 shared 初始化完成后，线程才读取输入并确定要投票的桶。",
      },
      {
        title: "shared atomicAdd 合并重复桶",
        sourceEntityIds: ["mapped-bins", "shared-bins-zero-base", "barrier-load"],
        targetEntityIds: ["shared-bins"],
        values: { "shared-bins": [0, 2, 1, 1] },
        transfers: [
          { from: "shared-bins-zero-base", to: "shared-bins", payload: [0, 0, 0, 0], label: "从已清零的 shared 桶开始累加" },
          { from: "mapped-bins", to: "shared-bins", payload: [1, 1, 2, 3], label: "四个线程向对应 shared 桶投票" },
          { from: "barrier-load", to: "shared-bins", payload: "released", label: "初始化屏障放行 shared 原子更新" },
        ],
        result: "block histogram = [0, 2, 1, 1]",
        explanation: "两个值 1 同时指向桶 1，原子加确保两票都被保留。",
      },
      {
        title: "等待 block 直方图完成",
        sourceEntityIds: ["shared-bins"],
        targetEntityIds: ["barrier-merge"],
        values: { "barrier-merge": "released" },
        result: "shared 计数总和 = 4",
        explanation: "第二次屏障保证任何线程合并全局桶前，全部 shared 原子更新已经结束。",
      },
      {
        title: "原子合并全局桶",
        sourceEntityIds: ["shared-bins", "global-bins-zero-base", "barrier-merge"],
        targetEntityIds: ["global-bins", "sample-count"],
        values: { "global-bins": [0, 2, 1, 1], "sample-count": 4 },
        outputEntityIds: ["global-bins", "sample-count"],
        transfers: [
          { from: "global-bins-zero-base", to: "global-bins", payload: [0, 0, 0, 0], label: "从清零后的全局桶开始合并" },
          { from: "shared-bins", to: "global-bins", payload: [0, 2, 1, 1], label: "每个非零 shared 桶执行一次全局 atomicAdd" },
          { from: "barrier-merge", to: "global-bins", payload: "released", label: "合并屏障放行全局原子更新" },
          { from: "shared-bins", to: "sample-count", payload: [0, 2, 1, 1], label: "复算所有桶计数总和" },
        ],
        result: "h = [0, 2, 1, 1]，sum(h) = 4",
        explanation: "每个非零 shared 桶只需一次全局原子加，最终桶总数等于样本数。",
      },
    ],
  },
};
