import type { CudaStoryboardDefinition } from "./storyboard.ts";

export const reshapeSceneDefinitions: Record<number, CudaStoryboardDefinition> = {
  601: {
    kind: "matrix",
    ariaLabel: "二乘三矩阵通过带 padding 的 shared tile 转置为三乘二",
    entities: [
      { id: "input", label: "输入 A (2x3)", role: "input", initialValue: [[1, 2, 3], [4, 5, 6]] },
      { id: "tile-owner", label: "输入 tile 坐标", role: "control", initialValue: "unmapped" },
      { id: "load-addresses", label: "合并读取地址", role: "control", initialValue: "pending" },
      { id: "shared", label: "shared tile (带 padding)", role: "intermediate", initialValue: "empty" },
      { id: "padding-column", label: "bank padding 列", role: "control", initialValue: "unused" },
      { id: "barrier", label: "块内屏障", role: "control", initialValue: "waiting" },
      { id: "swapped", label: "交换后的 (j,i)", role: "intermediate", initialValue: "pending" },
      { id: "write-addresses", label: "合并写地址", role: "control", initialValue: "pending" },
      { id: "output", label: "输出 B (3x2)", role: "output", initialValue: [[0, 0], [0, 0], [0, 0]] },
    ],
    formulaEntityIds: [["input", "shared"], ["swapped", "output"], ["tile-owner", "swapped"]],
    layout: {
      rows: 3,
      columns: 3,
      cellEntityIds: [
        ["input", "load-addresses", "shared"],
        ["tile-owner", "padding-column", "barrier"],
        ["swapped", "write-addresses", "output"],
      ],
    },
    steps: [
      {
        title: "线程块领取 2x3 输入 tile",
        sourceEntityIds: ["input"],
        targetEntityIds: ["tile-owner"],
        values: { "tile-owner": "rows 0..1, cols 0..2" },
        result: "六个有效线程覆盖 A 的六个元素",
        explanation: "非方阵样例让输入和输出边界检查不能被方形假设掩盖。",
      },
      {
        title: "按行合并读取到 padded shared",
        sourceEntityIds: ["input", "tile-owner"],
        targetEntityIds: ["load-addresses", "shared", "padding-column"],
        values: {
          "load-addresses": [0, 1, 2, 3, 4, 5],
          shared: [[1, 2, 3, "pad"], [4, 5, 6, "pad"]],
          "padding-column": "stride 4 avoids column bank conflict",
        },
        outputEntityIds: ["load-addresses", "shared", "padding-column"],
        transfers: [
          { from: "input", to: "shared", payload: [1, 2, 3, 4, 5, 6], label: "六个输入按行装入 shared" },
          { from: "tile-owner", to: "load-addresses", payload: "rows 0..1, cols 0..2", label: "tile 坐标生成连续读取地址" },
          { from: "tile-owner", to: "padding-column", payload: "2 rows", label: "每行末尾保留一个 padding 槽" },
        ],
        result: "shared = [[1,2,3,pad],[4,5,6,pad]]",
        explanation: "输入行连续读取，额外一列改变 shared 行跨度以分散转置列访问。",
      },
      {
        title: "屏障确认 tile 完整",
        sourceEntityIds: ["shared"],
        targetEntityIds: ["barrier"],
        values: { barrier: "released" },
        result: "六个有效 shared 槽位全部可读",
        explanation: "所有写入完成后才能交换索引读取其他线程负责的 shared 槽位。",
      },
      {
        title: "交换局部行列坐标",
        sourceEntityIds: ["shared", "barrier"],
        targetEntityIds: ["swapped"],
        values: { swapped: [[1, 4], [2, 5], [3, 6]] },
        result: "shared 按列读出 [[1,4],[2,5],[3,6]]",
        explanation: "线程使用 (j,i) 读取 shared，padding 只影响地址，不进入数值结果。",
      },
      {
        title: "按输出行合并写回 B",
        sourceEntityIds: ["swapped"],
        targetEntityIds: ["write-addresses", "output"],
        values: { "write-addresses": [0, 1, 2, 3, 4, 5], output: [[1, 4], [2, 5], [3, 6]] },
        outputEntityIds: ["output", "write-addresses"],
        result: "B = [[1,4],[2,5],[3,6]]",
        explanation: "交换后的每一输出行再次连续写入，六个元素各写一次且不越界。",
      },
    ],
  },
  602: {
    kind: "pipeline",
    ariaLabel: "Gather 随机读取与 ScatterAdd 重复索引原子求和",
    entities: [
      { id: "source", label: "Gather 源 Src", role: "input", initialValue: [10, 20, 30] },
      { id: "gather-index", label: "Gather 索引 g", role: "input", initialValue: [2, 0] },
      { id: "gather-read", label: "随机读取值", role: "intermediate", initialValue: [0, 0] },
      { id: "gather-output", label: "Gather 输出 y", role: "output", initialValue: [0, 0] },
      { id: "scatter-input", label: "ScatterAdd 输入 x", role: "input", initialValue: [10, 20, 30] },
      { id: "scatter-index", label: "ScatterAdd 索引 s", role: "input", initialValue: [1, 1, 0] },
      { id: "scatter-target-before-clear", label: "清零前 z 快照", role: "intermediate", initialValue: [9, 9, 9] },
      { id: "scatter-zero-base", label: "原子累加零基线", role: "intermediate", initialValue: [0, 0, 0] },
      { id: "scatter-target", label: "全局累加目标 z", role: "intermediate", initialValue: [9, 9, 9] },
      { id: "bounds", label: "索引范围检查", role: "control", initialValue: "unchecked" },
      { id: "atomic-log", label: "atomicAdd 更新", role: "intermediate", initialValue: "pending" },
      { id: "scatter-output", label: "最终 ScatterAdd z", role: "output", initialValue: [0, 0, 0] },
    ],
    formulaEntityIds: [["gather-index"], ["scatter-index"], ["gather-output"], ["scatter-target", "scatter-output"]],
    layout: {
      laneIds: ["Gather kernel", "全局内存", "ScatterAdd kernel"],
      laneByEntityId: {
        source: "全局内存",
        "gather-index": "Gather kernel",
        "gather-read": "Gather kernel",
        "gather-output": "全局内存",
        "scatter-input": "ScatterAdd kernel",
        "scatter-index": "ScatterAdd kernel",
        "scatter-target-before-clear": "全局内存",
        "scatter-zero-base": "全局内存",
        "scatter-target": "全局内存",
        bounds: "ScatterAdd kernel",
        "atomic-log": "ScatterAdd kernel",
        "scatter-output": "全局内存",
      },
      stageEntityIds: [
        "source", "gather-index", "gather-read", "gather-output", "scatter-input",
        "scatter-index", "scatter-target-before-clear", "scatter-zero-base", "scatter-target",
        "bounds", "atomic-log", "scatter-output",
      ],
    },
    steps: [
      {
        title: "读取 Gather 索引并随机取源值",
        sourceEntityIds: ["source", "gather-index"],
        targetEntityIds: ["gather-read"],
        values: { "gather-read": [30, 10] },
        result: "Src[g] = [Src[2], Src[0]] = [30, 10]",
        explanation: "索引数组连续读取，但它指向的源地址不连续；两个索引都在 0..2 范围内。",
      },
      {
        title: "独立写回 Gather 输出",
        sourceEntityIds: ["gather-read"],
        targetEntityIds: ["gather-output"],
        values: { "gather-output": [30, 10] },
        result: "y = [30, 10]",
        explanation: "每个 Gather 线程拥有唯一输出下标，所以不需要同步或原子操作。",
      },
      {
        title: "清零 ScatterAdd 目标",
        sourceEntityIds: ["scatter-target-before-clear"],
        targetEntityIds: ["scatter-target"],
        values: { "scatter-target": [0, 0, 0] },
        transfers: [{
          from: "scatter-target-before-clear",
          to: "scatter-target",
          payload: [9, 9, 9],
          label: "清零 kernel 覆盖旧哨兵值",
        }],
        result: "旧值 [9,9,9] 被清为 [0,0,0]",
        explanation: "清零在统计 kernel 前完成，确保本轮原子加不会叠加历史数据。",
      },
      {
        title: "读取 ScatterAdd 值和目标索引",
        sourceEntityIds: ["scatter-input", "scatter-index"],
        targetEntityIds: ["bounds"],
        values: { bounds: "s = [1,1,0], all in [0,3)" },
        result: "线程 0/1 冲突到 z[1]，线程 2 指向 z[0]",
        explanation: "范围检查通过后才允许发起全局原子更新，重复索引将按求和语义处理。",
      },
      {
        title: "atomicAdd 合并重复索引",
        sourceEntityIds: ["scatter-input", "scatter-index", "scatter-zero-base", "bounds"],
        targetEntityIds: ["atomic-log", "scatter-target"],
        values: {
          "atomic-log": ["z[1]+=10", "z[1]+=20", "z[0]+=30"],
          "scatter-target": [30, 30, 0],
        },
        outputEntityIds: ["scatter-target", "atomic-log"],
        transfers: [
          { from: "scatter-input", to: "atomic-log", payload: [10, 20, 30], label: "三个线程提供加数" },
          { from: "scatter-index", to: "atomic-log", payload: [1, 1, 0], label: "目标索引选择 z[1], z[1], z[0]" },
          { from: "bounds", to: "atomic-log", payload: "s = [1,1,0], all in [0,3)", label: "范围检查放行三个 atomicAdd" },
          { from: "scatter-zero-base", to: "scatter-target", payload: [0, 0, 0], label: "从清零后的 z 开始累加" },
          { from: "atomic-log", to: "scatter-target", payload: ["z[1]+=10", "z[1]+=20", "z[0]+=30"], label: "三个 atomicAdd 串行化到目标桶" },
        ],
        result: "原子合并后 z = [30, 30, 0]",
        explanation: "两个线程对 z[1] 的更新都保留，普通赋值无法保证这个结果。",
      },
      {
        title: "kernel 结束后读取唯一结果",
        sourceEntityIds: ["scatter-target"],
        targetEntityIds: ["scatter-output"],
        values: { "scatter-output": [30, 30, 0] },
        result: "ScatterAdd 输出 z = [30, 30, 0]",
        explanation: "kernel 边界让全部原子更新对后续读取可见，输出总和仍为 60。",
      },
    ],
  },
};
