import type { CudaStoryboardDefinition } from "./storyboard.ts";

export const elementWiseSceneDefinitions: Record<number, CudaStoryboardDefinition> = {
  102: {
    kind: "array",
    ariaLabel: "四个 CUDA 线程计算 y 等于 2x 加 1",
    entities: [
      { id: "thread-index", label: "线程全局下标 i", role: "control", initialValue: "unmapped" },
      { id: "input", label: "输入 x", role: "input", initialValue: [1, 2, 3, 4] },
      { id: "loaded", label: "线程寄存器 x_i", role: "intermediate", initialValue: [0, 0, 0, 0] },
      { id: "scale", label: "缩放参数 a", role: "input", initialValue: 2 },
      { id: "product", label: "乘积 a*x_i", role: "intermediate", initialValue: [0, 0, 0, 0] },
      { id: "bias", label: "偏置 b", role: "input", initialValue: 1 },
      { id: "biased-result", label: "乘加结果 a*x_i+b", role: "intermediate", initialValue: [0, 0, 0, 0] },
      { id: "output", label: "输出 y", role: "output", initialValue: [0, 0, 0, 0] },
    ],
    formulaEntityIds: [["input", "loaded"], ["output"], ["scale"], ["bias"]],
    layout: {
      orientation: "horizontal",
      groups: [
        { id: "mapping", label: "线程映射", entityIds: ["thread-index"] },
        { id: "global-input", label: "全局输入与参数", entityIds: ["input", "scale", "bias"] },
        { id: "registers", label: "寄存器计算", entityIds: ["loaded", "product", "biased-result"] },
        { id: "global-output", label: "全局输出", entityIds: ["output"] },
      ],
    },
    steps: [
      {
        title: "四个线程映射四个元素",
        sourceEntityIds: ["input"],
        targetEntityIds: ["thread-index"],
        values: { "thread-index": [0, 1, 2, 3] },
        result: "threadIdx 映射到 i = [0, 1, 2, 3]",
        explanation: "每个有效线程只负责相同下标的一个输入和一个输出。",
      },
      {
        title: "合并读取连续 x_i",
        sourceEntityIds: ["input"],
        targetEntityIds: ["loaded"],
        values: { loaded: [1, 2, 3, 4] },
        result: "寄存器得到 [1, 2, 3, 4]",
        explanation: "相邻线程读取相邻地址，因此一次内存事务能服务整个 warp。",
      },
      {
        title: "寄存器内执行乘加",
        sourceEntityIds: ["loaded", "scale", "bias"],
        targetEntityIds: ["product", "biased-result"],
        values: { product: [2, 4, 6, 8], "biased-result": [3, 5, 7, 9] },
        inputEntityIds: ["loaded", "scale", "bias"],
        outputEntityIds: ["product", "biased-result"],
        transfers: [
          { from: "loaded", to: "product", payload: [1, 2, 3, 4], label: "每个 x_i 进入乘法" },
          { from: "scale", to: "product", payload: 2, label: "统一乘缩放因子 a" },
          { from: "product", to: "biased-result", payload: [2, 4, 6, 8], label: "乘积进入加法" },
          { from: "bias", to: "biased-result", payload: 1, label: "统一加偏置 b" },
        ],
        expression: "2x_i+1",
        result: "先得 a*x_i = [2, 4, 6, 8]，再加 b 得 [3, 5, 7, 9]",
        explanation: "每个 lane 都先核对缩放乘积，再加同一个偏置；线程之间仍没有数据依赖。",
        debugEntityId: "product",
      },
      {
        title: "合并写回 y_i",
        sourceEntityIds: ["biased-result"],
        targetEntityIds: ["output"],
        values: { output: [3, 5, 7, 9] },
        result: "y = [3, 5, 7, 9]",
        explanation: "结果按原下标连续落回全局内存，读写两端都保持合并访问。",
      },
    ],
  },
  103: {
    kind: "array",
    ariaLabel: "LeakyReLU 对负数零和正数逐元素选通",
    entities: [
      { id: "lane", label: "元素下标 i", role: "control", initialValue: "unmapped" },
      { id: "input", label: "输入 x", role: "input", initialValue: [-2, 0, 3] },
      { id: "loaded", label: "寄存器 x_i", role: "intermediate", initialValue: [0, 0, 0] },
      { id: "positive", label: "max(x_i, 0)", role: "intermediate", initialValue: [0, 0, 0] },
      { id: "negative", label: "alpha * min(x_i, 0)", role: "intermediate", initialValue: [0, 0, 0] },
      { id: "alpha", label: "负半轴斜率 alpha", role: "input", initialValue: 0.1 },
      { id: "output", label: "激活输出 y", role: "output", initialValue: [0, 0, 0] },
    ],
    formulaEntityIds: [["input", "loaded"], ["output"], ["alpha"]],
    layout: {
      orientation: "horizontal",
      groups: [
        { id: "mapping", label: "线程", entityIds: ["lane"] },
        { id: "input", label: "输入", entityIds: ["input", "loaded"] },
        { id: "gate", label: "无分支选通", entityIds: ["positive", "negative", "alpha"] },
        { id: "output", label: "输出", entityIds: ["output"] },
      ],
    },
    steps: [
      {
        title: "线程绑定输入元素",
        sourceEntityIds: ["input"],
        targetEntityIds: ["lane"],
        values: { lane: [0, 1, 2] },
        result: "三个线程分别负责 -2、0、3",
        explanation: "映射是一线程一元素，三个激活值互不依赖。",
      },
      {
        title: "连续读取激活输入",
        sourceEntityIds: ["input"],
        targetEntityIds: ["loaded"],
        values: { loaded: [-2, 0, 3] },
        result: "寄存器 x_i = [-2, 0, 3]",
        explanation: "相邻 lane 从连续地址取值，不需要 shared memory 或块内同步。",
      },
      {
        title: "max/min 同时选通两条半轴",
        sourceEntityIds: ["loaded", "alpha"],
        targetEntityIds: ["positive", "negative"],
        values: { positive: [0, 0, 3], negative: [-0.2, 0, 0] },
        outputEntityIds: ["positive", "negative"],
        transfers: [
          { from: "loaded", to: "positive", payload: [-2, 0, 3], label: "x 进入正半轴 max" },
          { from: "loaded", to: "negative", payload: [-2, 0, 3], label: "x 进入负半轴 min" },
          { from: "alpha", to: "negative", payload: 0.1, label: "负半轴乘 alpha" },
        ],
        expression: "\\max(x_i,0)+0.1\\min(x_i,0)",
        result: "正半轴 [0, 0, 3]，缩放负半轴 [-0.2, 0, 0]",
        explanation: "max/min 让一个 warp 执行统一指令，同时保留 LeakyReLU 的负斜率。",
      },
      {
        title: "写回激活结果",
        sourceEntityIds: ["positive", "negative"],
        targetEntityIds: ["output"],
        values: { output: [-0.2, 0, 3] },
        result: "y = [-0.2, 0, 3]",
        explanation: "两部分逐元素相加后按原下标写回，零点保持为零。",
      },
    ],
  },
  104: {
    kind: "pipeline",
    ariaLabel: "同一组输入经过 Sigmoid 和 Tanh 特殊函数流水线",
    entities: [
      { id: "thread", label: "线程 i", role: "control", initialValue: "unmapped" },
      { id: "input", label: "输入 x", role: "input", initialValue: [-2, 0, 2] },
      { id: "loaded", label: "寄存器 x_i", role: "intermediate", initialValue: [0, 0, 0] },
      { id: "exp", label: "指数中间量", role: "operator", initialValue: "pending" },
      { id: "sigmoid", label: "Sigmoid 输出", role: "output", initialValue: [0, 0, 0] },
      { id: "tanh", label: "Tanh 输出", role: "output", initialValue: [0, 0, 0] },
      { id: "selected", label: "选定激活 y", role: "output", initialValue: [0, 0, 0] },
    ],
    formulaEntityIds: [["input", "loaded"], ["sigmoid"], ["tanh"], ["exp"]],
    layout: {
      laneIds: ["线程映射", "寄存器数学", "全局内存"],
      laneByEntityId: {
        thread: "线程映射",
        input: "全局内存",
        loaded: "寄存器数学",
        exp: "寄存器数学",
        sigmoid: "寄存器数学",
        tanh: "寄存器数学",
        selected: "全局内存",
      },
      stageEntityIds: ["thread", "input", "loaded", "exp", "sigmoid", "tanh", "selected"],
    },
    steps: [
      {
        title: "线程定位三个输入",
        sourceEntityIds: ["input"],
        targetEntityIds: ["thread"],
        values: { thread: [0, 1, 2] },
        result: "lane 0..2 映射 x = [-2, 0, 2]",
        explanation: "每个线程将只计算自己元素的特殊函数值。",
      },
      {
        title: "合并读取 x_i",
        sourceEntityIds: ["input"],
        targetEntityIds: ["loaded"],
        values: { loaded: [-2, 0, 2] },
        result: "寄存器输入 = [-2, 0, 2]",
        explanation: "读取仍是连续的，后续指数运算才是主要计算成本。",
      },
      {
        title: "执行稳定的指数变换",
        sourceEntityIds: ["loaded"],
        targetEntityIds: ["exp", "sigmoid", "tanh"],
        values: {
          exp: [7.3891, 1, 0.1353],
          sigmoid: [0.1192, 0.5, 0.8808],
          tanh: [-0.964, 0, 0.964],
        },
        outputEntityIds: ["exp", "sigmoid", "tanh"],
        result: "sigma = [0.1192, 0.5, 0.8808]；tanh = [-0.964, 0, 0.964]",
        explanation: "同样的输入产生两个有界输出，零点和正负对称性可以直接核对。",
      },
      {
        title: "选择 Sigmoid 并写回",
        sourceEntityIds: ["sigmoid"],
        targetEntityIds: ["selected"],
        values: { selected: [0.1192, 0.5, 0.8808] },
        result: "y = [0.1192, 0.5, 0.8808]",
        explanation: "本次 kernel 选择 Sigmoid 路径；三个结果都严格位于 0 和 1 之间。",
      },
    ],
  },
  105: {
    kind: "pipeline",
    ariaLabel: "五个 FP32 数以四元素向量和一个尾元素转换成 FP16",
    entities: [
      { id: "input", label: "FP32 输入", role: "input", initialValue: [1, 0.1, 65504, 0.00000001, 2.5] },
      { id: "vector-owner", label: "线程向量分工", role: "control", initialValue: "unmapped" },
      { id: "vector-load", label: "float4 主段", role: "intermediate", initialValue: [0, 0, 0, 0] },
      { id: "tail-load", label: "标量尾元素", role: "intermediate", initialValue: 0 },
      { id: "half-main", label: "FP16 主段", role: "intermediate", initialValue: [0, 0, 0, 0] },
      { id: "tail-mask", label: "尾部边界掩码", role: "control", initialValue: "closed" },
      { id: "half-tail", label: "FP16 尾元素", role: "intermediate", initialValue: 0 },
      { id: "output", label: "紧凑 FP16 输出", role: "output", initialValue: [0, 0, 0, 0, 0] },
    ],
    formulaEntityIds: [["input", "vector-load"], ["output"], ["half-main", "half-tail"]],
    layout: {
      laneIds: ["全局 FP32", "转换单元", "全局 FP16"],
      laneByEntityId: {
        input: "全局 FP32",
        "vector-owner": "转换单元",
        "vector-load": "转换单元",
        "tail-load": "转换单元",
        "half-main": "转换单元",
        "tail-mask": "转换单元",
        "half-tail": "转换单元",
        output: "全局 FP16",
      },
      stageEntityIds: ["input", "vector-owner", "vector-load", "tail-load", "half-main", "tail-mask", "half-tail", "output"],
    },
    steps: [
      {
        title: "按宽度 4 分配主段和尾部",
        sourceEntityIds: ["input"],
        targetEntityIds: ["vector-owner", "tail-mask"],
        values: { "vector-owner": "float4[0..3]", "tail-mask": "index 4 valid" },
        result: "4 个主元素 + 1 个有效尾元素",
        explanation: "长度 5 不能整除向量宽度 4，因此尾线程必须显式检查边界。",
      },
      {
        title: "向量化读取主段并受掩码读取尾部",
        sourceEntityIds: ["input"],
        targetEntityIds: ["vector-load", "tail-load"],
        values: { "vector-load": [1, 0.1, 65504, 0.00000001], "tail-load": 2.5 },
        outputEntityIds: ["vector-load", "tail-load"],
        transfers: [
          { from: "input", to: "vector-load", payload: [1, 0.1, 65504, 0.00000001], label: "对齐读取 input[0..3]" },
          { from: "input", to: "tail-load", payload: 2.5, label: "掩码允许读取 input[4]" },
        ],
        result: "float4 = [1, 0.1, 65504, 1e-8]；tail = 2.5",
        explanation: "对齐的 float4 读取覆盖前四项，边界掩码只允许标量路径读取第五项。",
      },
      {
        title: "逐 lane 舍入到 FP16",
        sourceEntityIds: ["vector-load", "tail-load", "tail-mask"],
        targetEntityIds: ["half-main", "half-tail"],
        values: { "half-main": [1, 0.09998, 65504, 0], "half-tail": 2.5 },
        inputEntityIds: ["vector-load", "tail-load", "tail-mask"],
        transfers: [
          { from: "vector-load", to: "half-main", payload: [1, 0.1, 65504, 0.00000001], label: "四个主段值逐 lane 转换" },
          { from: "tail-load", to: "half-tail", payload: 2.5, label: "标量尾值转换" },
          { from: "tail-mask", to: "half-tail", payload: "index 4 valid", label: "有效尾掩码保护标量转换" },
        ],
        result: "0.1 舍入为 0.09998，1e-8 下溢为 0，尾值 2.5 保留",
        explanation: "转换会改变不可精确表示的数，并可能让极小值下溢；尾元素走受掩码保护的标量路径。",
      },
      {
        title: "写回紧凑 half 数组",
        sourceEntityIds: ["half-main", "half-tail"],
        targetEntityIds: ["output"],
        values: { output: [1, 0.09998, 65504, 0, 2.5] },
        result: "FP16 输出 = [1, 0.09998, 65504, 0, 2.5]",
        explanation: "主段与尾元素各写一次，没有漏写第五项，也没有越界访问。",
      },
    ],
  },
  106: {
    kind: "pipeline",
    ariaLabel: "固定 Philox 随机数生成掩码并计算 inverted dropout",
    entities: [
      { id: "seed", label: "Philox seed", role: "input", initialValue: 7 },
      { id: "thread-index", label: "线程全局下标 i", role: "control", initialValue: [0, 1, 2, 3] },
      { id: "counter", label: "Philox counter", role: "control", initialValue: "uninitialized" },
      { id: "input", label: "输入 x", role: "input", initialValue: [1, 1, 1, 1] },
      { id: "loaded", label: "寄存器 x_i", role: "intermediate", initialValue: [0, 0, 0, 0] },
      { id: "random", label: "均匀随机数 u", role: "intermediate", initialValue: [0, 0, 0, 0] },
      { id: "probability", label: "丢弃概率 p", role: "input", initialValue: 0.5 },
      { id: "mask", label: "保留掩码 m", role: "intermediate", initialValue: [0, 0, 0, 0] },
      { id: "scale", label: "inverted scale", role: "operator", initialValue: 1 },
      { id: "output", label: "Dropout 输出 y", role: "output", initialValue: [0, 0, 0, 0] },
    ],
    formulaEntityIds: [["random"], ["probability"], ["mask"], ["output"]],
    layout: {
      laneIds: ["随机数", "数据", "输出"],
      laneByEntityId: {
        seed: "随机数",
        "thread-index": "随机数",
        counter: "随机数",
        input: "数据",
        loaded: "数据",
        random: "随机数",
        probability: "数据",
        mask: "随机数",
        scale: "数据",
        output: "输出",
      },
      stageEntityIds: ["seed", "thread-index", "counter", "input", "loaded", "random", "probability", "mask", "scale", "output"],
    },
    steps: [
      {
        title: "由 seed 和下标构造独立 counter",
        sourceEntityIds: ["seed", "thread-index"],
        targetEntityIds: ["counter"],
        values: { counter: ["seed:7/0", "seed:7/1", "seed:7/2", "seed:7/3"] },
        transfers: [
          { from: "seed", to: "counter", payload: 7, label: "固定 seed 进入 Philox counter" },
          { from: "thread-index", to: "counter", payload: [0, 1, 2, 3], label: "线程下标选择互不重叠的 counter" },
        ],
        result: "四个线程得到互不重叠的计数器",
        explanation: "全局下标进入 counter，使固定 seed 可复现，同时避免线程共享随机状态。",
      },
      {
        title: "读取输入并生成均匀随机数",
        sourceEntityIds: ["counter", "input"],
        targetEntityIds: ["random", "loaded"],
        values: { random: [0.8, 0.2, 0.3, 0.9], loaded: [1, 1, 1, 1] },
        outputEntityIds: ["random", "loaded"],
        transfers: [
          { from: "counter", to: "random", payload: ["seed:7/0", "seed:7/1", "seed:7/2", "seed:7/3"], label: "每个 counter 生成一个确定随机数" },
          { from: "input", to: "loaded", payload: [1, 1, 1, 1], label: "连续读取四个输入元素" },
        ],
        result: "u = [0.8, 0.2, 0.3, 0.9]",
        explanation: "每个线程读取自己的 x_i，并由自己的 counter 得到一个确定的随机数。",
      },
      {
        title: "比较 u_i 与 p 生成掩码",
        sourceEntityIds: ["random", "probability"],
        targetEntityIds: ["mask", "scale"],
        values: { mask: [1, 0, 0, 1], scale: 2 },
        outputEntityIds: ["mask", "scale"],
        transfers: [
          { from: "random", to: "mask", payload: [0.8, 0.2, 0.3, 0.9], label: "逐项随机数进入阈值比较" },
          { from: "probability", to: "mask", payload: 0.5, label: "丢弃概率作为比较阈值" },
          { from: "probability", to: "scale", payload: 0.5, label: "由 p 计算 1/(1-p)" },
        ],
        result: "m = [1, 0, 0, 1]，1/(1-p) = 2",
        explanation: "u_i 大于等于 0.5 的元素保留；其余元素归零，无需线程同步。",
      },
      {
        title: "缩放保留项并写回",
        sourceEntityIds: ["loaded", "mask", "scale"],
        targetEntityIds: ["output"],
        values: { output: [2, 0, 0, 2] },
        expression: "y_i=m_ix_i/(1-p)",
        result: "y = [2, 0, 0, 2]",
        explanation: "保留项乘 2，使随机丢弃后的期望仍与输入一致。",
      },
    ],
  },
};
