import type { CudaStoryboardDefinition } from "./storyboard.ts";

export const matrixSceneDefinitions: Record<number, CudaStoryboardDefinition> = {
  401: {
    kind: "matrix",
    ariaLabel: "SGEMM 用 ping pong shared tile 计算二乘二输出矩阵",
    entities: [
      { id: "a", label: "全局矩阵 A", role: "input", initialValue: [[1, 2, 3, 4], [5, 6, 7, 8]] },
      { id: "b", label: "全局矩阵 B", role: "input", initialValue: [[1, 2], [0, 1], [1, 0], [2, 1]] },
      { id: "c-tile", label: "C tile 坐标", role: "control", initialValue: "rows 0..1, cols 0..1" },
      { id: "ping-a", label: "ping A tile", role: "intermediate", initialValue: "empty" },
      { id: "ping-b", label: "ping B tile", role: "intermediate", initialValue: "empty" },
      { id: "pong-a", label: "pong A tile", role: "intermediate", initialValue: "empty" },
      { id: "pong-b", label: "pong B tile", role: "intermediate", initialValue: "empty" },
      { id: "k-range", label: "归约维 K", role: "control", initialValue: 4 },
      { id: "tile-width", label: "每个 K tile 宽度", role: "control", initialValue: 2 },
      { id: "buffer-state", label: "异步拷贝与屏障", role: "control", initialValue: "idle" },
      { id: "accumulator", label: "寄存器累加器", role: "intermediate", initialValue: "uninitialized" },
      { id: "accumulator-after-k0", label: "首个 K tile 后累加器快照", role: "intermediate", initialValue: "pending" },
      { id: "k1-contribution", label: "第二个 K tile 贡献", role: "intermediate", initialValue: "pending" },
      { id: "c", label: "输出矩阵 C", role: "output", initialValue: [[0, 0], [0, 0]] },
    ],
    formulaEntityIds: [["a", "ping-a", "pong-a"], ["b", "ping-b", "pong-b"], ["accumulator", "c"], ["k-range"]],
    layout: {
      cellEntityIds: [
        ["a", "ping-a", "pong-a", "accumulator-after-k0", "accumulator", "c", "k-range"],
        ["b", "ping-b", "pong-b", "k1-contribution", "buffer-state", "c-tile", "tile-width"],
      ],
      rows: 2,
      columns: 7,
    },
    steps: [
      {
        title: "映射 C tile 并清零累加器",
        sourceEntityIds: ["c-tile", "k-range", "tile-width"],
        targetEntityIds: ["accumulator"],
        values: { accumulator: [[0, 0], [0, 0]] },
        transfers: [
          {
            from: "c-tile",
            to: "accumulator",
            payload: "rows 0..1, cols 0..1",
            label: "输出 tile 坐标分配四个寄存器",
          },
          { from: "k-range", to: "accumulator", payload: 4, label: "K=4 决定点积长度" },
          { from: "tile-width", to: "accumulator", payload: 2, label: "tile 宽度 2 决定共两轮" },
        ],
        result: "K=4 按宽度 2 分成两轮；2x2 C tile 累加器清零",
        explanation: "线程块先映射输出坐标，并明确点积长度 K=4 将由两个 K tile 完成。",
      },
      {
        title: "预取 K tile 0 到 ping",
        sourceEntityIds: ["a", "b"],
        targetEntityIds: ["ping-a", "ping-b", "buffer-state"],
        values: {
          "ping-a": [[1, 2], [5, 6]],
          "ping-b": [[1, 2], [0, 1]],
          "buffer-state": "ping ready after __syncthreads()",
        },
        outputEntityIds: ["ping-a", "ping-b", "buffer-state"],
        transfers: [
          { from: "a", to: "ping-a", payload: [1, 2, 5, 6], label: "A[:,0:2] 合并装入 ping" },
          { from: "b", to: "ping-b", payload: [1, 2, 0, 1], label: "B[0:2,:] 合并装入 ping" },
          { from: "ping-a", to: "buffer-state", payload: "ping A ready", label: "ping A 写入完成" },
          { from: "ping-b", to: "buffer-state", payload: "ping B ready", label: "ping B 写入完成" },
        ],
        result: "ping 持有 K=0..1 的 A/B tile",
        explanation: "合并读取完成并经过块内同步后，所有线程才能从 ping tile 做乘加。",
      },
      {
        title: "计算 ping，同时预取 pong",
        sourceEntityIds: ["ping-a", "ping-b", "a", "b"],
        targetEntityIds: ["accumulator", "accumulator-after-k0", "pong-a", "pong-b"],
        values: {
          accumulator: [[1, 4], [5, 16]],
          "accumulator-after-k0": [[1, 4], [5, 16]],
          "pong-a": [[3, 4], [7, 8]],
          "pong-b": [[1, 0], [2, 1]],
        },
        outputEntityIds: ["accumulator", "accumulator-after-k0", "pong-a", "pong-b"],
        transfers: [
          { from: "ping-a", to: "accumulator", payload: [1, 2, 5, 6], label: "ping A 参与首轮 FMA" },
          { from: "ping-b", to: "accumulator", payload: [1, 2, 0, 1], label: "ping B 参与首轮 FMA" },
          { from: "accumulator", to: "accumulator-after-k0", payload: [1, 4, 5, 16], label: "保存首轮累加器快照" },
          { from: "a", to: "pong-a", payload: [3, 4, 7, 8], label: "并发预取 A[:,2:4]" },
          { from: "b", to: "pong-b", payload: [1, 0, 2, 1], label: "并发预取 B[2:4,:]" },
        ],
        result: "首个 K tile 后 acc = [[1,4],[5,16]]；pong 预取完成",
        explanation: "当前 ping tile 供 FMA 使用时，cp.async 把下一段 K 数据搬进独立的 pong 缓冲。",
      },
      {
        title: "等待异步拷贝并交换缓冲",
        sourceEntityIds: ["pong-a", "pong-b", "accumulator"],
        targetEntityIds: ["buffer-state"],
        values: { "buffer-state": "pong ready; ping reusable" },
        transfers: [
          { from: "pong-a", to: "buffer-state", payload: "pong A copy complete", label: "等待 pong A 异步拷贝" },
          { from: "pong-b", to: "buffer-state", payload: "pong B copy complete", label: "等待 pong B 异步拷贝" },
          { from: "accumulator", to: "buffer-state", payload: "K tile 0 FMA complete", label: "确认 ping 读取结束" },
        ],
        result: "pong 成为当前 tile，ping 可以复用",
        explanation: "等待和块内屏障同时保护新 tile 的完整性与旧 tile 的读取完成。",
      },
      {
        title: "计算第二个 K tile",
        sourceEntityIds: ["pong-a", "pong-b", "accumulator-after-k0"],
        targetEntityIds: ["k1-contribution", "accumulator", "buffer-state"],
        values: {
          "k1-contribution": [[11, 4], [23, 8]],
          accumulator: [[12, 8], [28, 24]],
          "buffer-state": "all K tiles consumed",
        },
        outputEntityIds: ["k1-contribution", "accumulator", "buffer-state"],
        transfers: [
          { from: "pong-a", to: "k1-contribution", payload: [3, 4, 7, 8], label: "pong A 参与第二轮 FMA" },
          { from: "pong-b", to: "k1-contribution", payload: [1, 0, 2, 1], label: "pong B 参与第二轮 FMA" },
          { from: "accumulator-after-k0", to: "accumulator", payload: [1, 4, 5, 16], label: "读取首轮累加器快照" },
          { from: "k1-contribution", to: "accumulator", payload: [11, 4, 23, 8], label: "累加第二轮贡献" },
          { from: "pong-a", to: "buffer-state", payload: "pong A consumed", label: "pong A 读取结束" },
          { from: "pong-b", to: "buffer-state", payload: "pong B consumed", label: "pong B 读取结束" },
        ],
        expression: "C^{(1)}=C^{(0)}+A_1B_1",
        result: "最终 acc = [[12,8],[28,24]]",
        explanation: "第二个 tile 的贡献 [[11,4],[23,8]] 加到首轮前缀，完成 K 维点积。",
      },
      {
        title: "合并写回 C tile",
        sourceEntityIds: ["accumulator"],
        targetEntityIds: ["c"],
        values: { c: [[12, 8], [28, 24]] },
        result: "C = [[12,8],[28,24]]",
        explanation: "每个线程把寄存器结果写到连续输出区域，中间 tile 从未落到全局内存。",
      },
    ],
  },
  402: {
    kind: "matrix",
    ariaLabel: "一个 warp 计算矩阵行与向量的点积三十二",
    entities: [
      { id: "row", label: "矩阵行 A_i", role: "input", initialValue: [1, 2, 3] },
      { id: "vector", label: "向量 x", role: "input", initialValue: [4, 5, 6] },
      { id: "warp-owner", label: "warp 行映射", role: "control", initialValue: "unassigned" },
      { id: "lane-addresses", label: "lane 读取列", role: "control", initialValue: "pending" },
      { id: "lane-products", label: "lane 局部乘积", role: "intermediate", initialValue: [0, 0, 0] },
      { id: "tail-mask", label: "越界 lane 掩码", role: "control", initialValue: "pending" },
      { id: "shuffle", label: "warp shuffle 部分和", role: "intermediate", initialValue: "pending" },
      { id: "lane-zero", label: "lane 0 结果", role: "intermediate", initialValue: 0 },
      { id: "output", label: "输出 y_i", role: "output", initialValue: 0 },
    ],
    formulaEntityIds: [["row", "lane-products"], ["vector", "lane-products"], ["lane-zero", "output"], ["row", "tail-mask"]],
    layout: {
      rows: 3,
      columns: 3,
      cellEntityIds: [
        ["row", "vector", "warp-owner"],
        ["lane-addresses", "lane-products", "tail-mask"],
        ["shuffle", "lane-zero", "output"],
      ],
    },
    steps: [
      {
        title: "一个 warp 领取一行",
        sourceEntityIds: ["row"],
        targetEntityIds: ["warp-owner"],
        values: { "warp-owner": "warp 0 -> row 0" },
        result: "warp 0 独占 A 的第 0 行",
        explanation: "一行只由一个 warp 归约，因此不需要跨 warp 的 shared memory。",
      },
      {
        title: "lane 合并读取 A 与 x",
        sourceEntityIds: ["row", "vector"],
        targetEntityIds: ["lane-addresses"],
        values: { "lane-addresses": ["lane0:j0", "lane1:j1", "lane2:j2"] },
        result: "lane 0/1/2 读取列 0/1/2",
        explanation: "行主序 A 的相邻列由相邻 lane 读取，x 也按相同下标访问。",
      },
      {
        title: "寄存器累加局部乘积",
        sourceEntityIds: ["row", "vector", "lane-addresses"],
        targetEntityIds: ["lane-products", "tail-mask"],
        values: { "lane-products": [4, 10, 18], "tail-mask": "lanes 3..31 contribute 0" },
        outputEntityIds: ["lane-products", "tail-mask"],
        transfers: [
          { from: "row", to: "lane-products", payload: [1, 2, 3], label: "lane 读取 A 行元素" },
          { from: "vector", to: "lane-products", payload: [4, 5, 6], label: "lane 读取 x 元素" },
          { from: "lane-addresses", to: "lane-products", payload: ["lane0:j0", "lane1:j1", "lane2:j2"], label: "有效 lane 配对同列操作数" },
          { from: "lane-addresses", to: "tail-mask", payload: "lanes 3..31 out of range", label: "其余 lane 由边界掩码置零" },
        ],
        result: "局部乘积 = [4, 10, 18]，尾 lane = 0",
        explanation: "有效 lane 计算 A_ij*x_j，超过 N 的 lane 由掩码贡献零。",
      },
      {
        title: "warp shuffle 归约局部和",
        sourceEntityIds: ["lane-products"],
        targetEntityIds: ["shuffle", "lane-zero"],
        values: { shuffle: [32, 28, 18], "lane-zero": 32 },
        outputEntityIds: ["shuffle", "lane-zero"],
        result: "lane 0 得到 4 + 10 + 18 = 32",
        explanation: "shuffle 只在同一 warp 内交换寄存器值，不需要 __syncthreads()。",
      },
      {
        title: "lane 0 唯一写回 y_i",
        sourceEntityIds: ["lane-zero"],
        targetEntityIds: ["output"],
        values: { output: 32 },
        result: "y_0 = 32",
        explanation: "只有 lane 0 写这一行输出，避免多个 lane 对同一地址竞争。",
      },
    ],
  },
  403: {
    kind: "matrix",
    ariaLabel: "矩阵乘法结果在寄存器融合偏置和 ReLU 后写回",
    entities: [
      { id: "a", label: "矩阵 A", role: "input", initialValue: [[1, -2], [3, 1]] },
      { id: "b", label: "矩阵 B", role: "input", initialValue: [[2, 1], [-1, 2]] },
      { id: "bias", label: "列偏置 b", role: "input", initialValue: [-5, 1] },
      { id: "tile-owner", label: "输出 tile 映射", role: "control", initialValue: "Y[0:2,0:2]" },
      { id: "shared-a", label: "shared A tile", role: "intermediate", initialValue: "empty" },
      { id: "shared-b", label: "shared B tile", role: "intermediate", initialValue: "empty" },
      { id: "load-barrier", label: "装载屏障", role: "control", initialValue: "waiting" },
      { id: "accumulator", label: "MatMul 累加器", role: "intermediate", initialValue: "uninitialized" },
      { id: "reuse-barrier", label: "复用屏障", role: "control", initialValue: "waiting" },
      { id: "bias-added", label: "加列偏置后 C+b", role: "intermediate", initialValue: "pending" },
      { id: "relu-mask", label: "ReLU 正值掩码", role: "control", initialValue: "pending" },
      { id: "epilogue", label: "Bias + ReLU 寄存器", role: "intermediate", initialValue: "pending" },
      { id: "output", label: "最终 Y", role: "output", initialValue: [[0, 0], [0, 0]] },
      { id: "k-range", label: "归约维 K", role: "control", initialValue: 2 },
    ],
    formulaEntityIds: [["a", "b", "accumulator"], ["bias", "epilogue"], ["epilogue", "output"], ["k-range", "accumulator"]],
    layout: {
      rows: 2,
      columns: 7,
      cellEntityIds: [
        ["a", "shared-a", "accumulator", "bias-added", "relu-mask", "epilogue", "output"],
        ["b", "shared-b", "load-barrier", "reuse-barrier", "bias", "tile-owner", "k-range"],
      ],
    },
    steps: [
      {
        title: "领取输出 tile 并清零寄存器",
        sourceEntityIds: ["tile-owner", "k-range"],
        targetEntityIds: ["accumulator"],
        values: { accumulator: [[0, 0], [0, 0]] },
        transfers: [
          { from: "tile-owner", to: "accumulator", payload: "Y[0:2,0:2]", label: "映射四个输出坐标" },
          { from: "k-range", to: "accumulator", payload: 2, label: "K=2 决定乘加轮数" },
        ],
        result: "四个输出累加器清零",
        explanation: "线程块负责完整 2x2 输出，K=2 将在 shared tile 中归约。",
      },
      {
        title: "装载 A/B tile 并补边界",
        sourceEntityIds: ["a", "b"],
        targetEntityIds: ["shared-a", "shared-b"],
        values: { "shared-a": [[1, -2], [3, 1]], "shared-b": [[2, 1], [-1, 2]] },
        transfers: [
          { from: "a", to: "shared-a", payload: [1, -2, 3, 1], label: "A tile 合并装载" },
          { from: "b", to: "shared-b", payload: [2, 1, -1, 2], label: "B tile 合并装载" },
        ],
        result: "shared A/B tile 完整可用",
        explanation: "有效位置合并读取；若 tile 越界，同一路径会把对应 shared 槽位置零。",
      },
      {
        title: "首个屏障后执行 FMA",
        sourceEntityIds: ["shared-a", "shared-b"],
        targetEntityIds: ["load-barrier", "accumulator"],
        values: { "load-barrier": "released", accumulator: [[4, -3], [5, 5]] },
        outputEntityIds: ["accumulator", "load-barrier"],
        transfers: [
          { from: "shared-a", to: "accumulator", payload: [1, -2, 3, 1], label: "A tile 进入寄存器 FMA" },
          { from: "shared-b", to: "accumulator", payload: [2, 1, -1, 2], label: "B tile 进入寄存器 FMA" },
          { from: "shared-a", to: "load-barrier", payload: "A tile ready", label: "A tile 写入完成" },
          { from: "shared-b", to: "load-barrier", payload: "B tile ready", label: "B tile 写入完成" },
        ],
        result: "A*B = [[4,-3],[5,5]] 留在寄存器",
        explanation: "屏障先保证 tile 完整，然后线程沿 K 维执行两轮乘加。",
      },
      {
        title: "第二个屏障保护 shared 复用",
        sourceEntityIds: ["accumulator", "shared-a", "shared-b"],
        targetEntityIds: ["reuse-barrier"],
        values: { "reuse-barrier": "released after all reads" },
        result: "本轮 shared 读取全部结束",
        explanation: "任何线程覆盖 shared tile 前，都要等同一 block 的其他线程结束读取。",
      },
      {
        title: "寄存器融合 Bias 与 ReLU",
        sourceEntityIds: ["accumulator", "bias"],
        targetEntityIds: ["bias-added", "relu-mask", "epilogue"],
        values: {
          "bias-added": [[-1, -2], [0, 6]],
          "relu-mask": [[0, 0], [0, 1]],
          epilogue: [[0, 0], [0, 6]],
        },
        outputEntityIds: ["bias-added", "relu-mask", "epilogue"],
        transfers: [
          { from: "accumulator", to: "bias-added", payload: [[4, -3], [5, 5]], label: "MatMul 累加器进入列偏置加法" },
          { from: "bias", to: "bias-added", payload: [-5, 1], label: "b_j 按列广播" },
          { from: "bias-added", to: "relu-mask", payload: [[-1, -2], [0, 6]], label: "逐项判断是否大于零" },
          { from: "bias-added", to: "epilogue", payload: [[-1, -2], [0, 6]], label: "偏置结果进入 ReLU" },
          { from: "relu-mask", to: "epilogue", payload: [[0, 0], [0, 1]], label: "掩码保留唯一正值 6" },
        ],
        expression: "\\max(0,C_{ij}+b_j)",
        result: "加偏置后 [[-1,-2],[0,6]]，ReLU 后 [[0,0],[0,6]]",
        explanation: "偏置按输出列广播，负数立即截零，中间矩阵不写回全局内存。",
      },
      {
        title: "合并写回融合输出",
        sourceEntityIds: ["epilogue"],
        targetEntityIds: ["output"],
        values: { output: [[0, 0], [0, 6]] },
        result: "Y = [[0,0],[0,6]]",
        explanation: "一次全局写回同时完成 MatMul、Bias 和 ReLU 三个数学阶段。",
      },
    ],
  },
};
