import type { CudaStoryboardDefinition } from "./storyboard.ts";

export const normalizationSceneDefinitions: Record<number, CudaStoryboardDefinition> = {
  701: {
    kind: "pipeline",
    ariaLabel: "一行四维特征经过统计归约归一化和仿射变换",
    entities: [
      { id: "block-owner", label: "block 行映射", role: "control", initialValue: "unassigned" },
      { id: "input", label: "一行特征 x", role: "input", initialValue: [1, 2, 3, 4] },
      { id: "hidden-size", label: "隐藏维 H", role: "control", initialValue: 4 },
      { id: "local-stats", label: "线程局部 (count,mean,M2)", role: "intermediate", initialValue: "pending" },
      { id: "mean", label: "行均值 mu", role: "intermediate", initialValue: 0 },
      { id: "variance", label: "行方差 sigma^2", role: "intermediate", initialValue: 0 },
      { id: "epsilon", label: "稳定项 epsilon", role: "input", initialValue: 0.00001 },
      { id: "normalized", label: "归一化 hat{x}", role: "intermediate", initialValue: [0, 0, 0, 0] },
      { id: "gamma-beta", label: "仿射参数 (gamma,beta)", role: "input", initialValue: "gamma=[1,1.5,0.5,2], beta=[0,1,-1,0]" },
      { id: "output", label: "LayerNorm 输出 y", role: "output", initialValue: [0, 0, 0, 0] },
    ],
    formulaEntityIds: [
      ["hidden-size"], ["mean"], ["variance"], ["normalized"], ["gamma-beta"], ["epsilon"],
    ],
    layout: {
      laneIds: ["全局内存", "线程与 warp", "block 统计", "寄存器 epilogue"],
      laneByEntityId: {
        "block-owner": "线程与 warp",
        input: "全局内存",
        "hidden-size": "线程与 warp",
        "local-stats": "线程与 warp",
        mean: "block 统计",
        variance: "block 统计",
        epsilon: "寄存器 epilogue",
        normalized: "寄存器 epilogue",
        "gamma-beta": "全局内存",
        output: "全局内存",
      },
      stageEntityIds: ["block-owner", "input", "hidden-size", "local-stats", "mean", "variance", "epsilon", "normalized", "gamma-beta", "output"],
    },
    steps: [
      {
        title: "一个 block 领取一行特征",
        sourceEntityIds: ["input", "hidden-size"],
        targetEntityIds: ["block-owner"],
        values: { "block-owner": "block 0 -> row 0" },
        result: "block 0 独立归一化 x = [1,2,3,4]",
        explanation: "LayerNorm 的统计范围是这一行 H=4 个隐藏维，不跨 batch。",
      },
      {
        title: "合并读取并形成稳定局部统计",
        sourceEntityIds: ["input"],
        targetEntityIds: ["local-stats"],
        values: { "local-stats": ["(2,1.5,0.5)", "(2,3.5,0.5)"] },
        result: "两个线程组分别统计 [1,2] 与 [3,4]",
        explanation: "局部 count、mean 和 M2 可用 Welford 合并，避免 E[x^2]-E[x]^2 的相消。",
      },
      {
        title: "warp/shared 归约均值与方差",
        sourceEntityIds: ["local-stats", "hidden-size"],
        targetEntityIds: ["mean", "variance"],
        values: { mean: 2.5, variance: 1.25 },
        transfers: [
          { from: "local-stats", to: "mean", payload: ["(2,1.5,0.5)", "(2,3.5,0.5)"], label: "合并局部 count 与 mean" },
          { from: "local-stats", to: "variance", payload: ["(2,1.5,0.5)", "(2,3.5,0.5)"], label: "合并局部 M2" },
          { from: "hidden-size", to: "mean", payload: 4, label: "均值除以 H" },
          { from: "hidden-size", to: "variance", payload: 4, label: "总体方差除以 H" },
        ],
        result: "mu = 2.5，sigma^2 = 1.25",
        explanation: "warp 部分统计经 shared memory 和块内屏障合成完整一行的总体方差。",
      },
      {
        title: "广播统计量并归一化",
        sourceEntityIds: ["input", "mean", "variance", "epsilon"],
        targetEntityIds: ["normalized"],
        values: { normalized: [-1.3416, -0.4472, 0.4472, 1.3416] },
        expression: "(x_i-2.5)/\\sqrt{1.25+10^{-5}}",
        result: "hat{x} ≈ [-1.3416,-0.4472,0.4472,1.3416]",
        explanation: "每个线程复用同一行统计量，epsilon 保证分母即使在常量行也非零。",
      },
      {
        title: "融合 gamma/beta 并写回",
        sourceEntityIds: ["normalized", "gamma-beta"],
        targetEntityIds: ["output"],
        values: { output: [-1.3416, 0.3292, -0.7764, 2.6832] },
        result: "y ≈ [-1.3416,0.3292,-0.7764,2.6832]",
        explanation: "逐维 gamma 和 beta 在寄存器中完成仿射变换；最终输出不再要求均值为零。",
      },
    ],
  },
  702: {
    kind: "pipeline",
    ariaLabel: "大 logits 先减行最大值再归一化为稳定 Softmax 概率",
    entities: [
      { id: "row-owner", label: "warp/block 行映射", role: "control", initialValue: "unassigned" },
      { id: "logits", label: "输入 logits x", role: "input", initialValue: [1000, 1001, 1002] },
      { id: "row-max", label: "行最大值 m", role: "intermediate", initialValue: "pending" },
      { id: "shifted", label: "移位 logits", role: "intermediate", initialValue: [0, 0, 0] },
      { id: "exponentials", label: "稳定指数值", role: "intermediate", initialValue: [0, 0, 0] },
      { id: "local-sum", label: "线程局部指数和", role: "intermediate", initialValue: [0, 0, 0] },
      { id: "denominator", label: "全行指数总和", role: "intermediate", initialValue: 0 },
      { id: "probabilities", label: "概率 p", role: "output", initialValue: [0, 0, 0] },
      { id: "probability-sum", label: "概率总和", role: "control", initialValue: 0 },
    ],
    formulaEntityIds: [["logits", "shifted"], ["row-max"], ["probabilities"], ["denominator"]],
    layout: {
      laneIds: ["全局内存", "最大值归约", "指数与求和", "归一化"],
      laneByEntityId: {
        "row-owner": "最大值归约",
        logits: "全局内存",
        "row-max": "最大值归约",
        shifted: "指数与求和",
        exponentials: "指数与求和",
        "local-sum": "指数与求和",
        denominator: "指数与求和",
        probabilities: "归一化",
        "probability-sum": "归一化",
      },
      stageEntityIds: ["row-owner", "logits", "row-max", "shifted", "exponentials", "local-sum", "denominator", "probabilities", "probability-sum"],
    },
    steps: [
      {
        title: "一个 warp 或 block 领取 logits 行",
        sourceEntityIds: ["logits"],
        targetEntityIds: ["row-owner"],
        values: { "row-owner": "row 0 -> lanes 0..2" },
        result: "三个有效 lane 负责 [1000,1001,1002]",
        explanation: "同一执行组将共享一个最大值和一个归一化分母。",
      },
      {
        title: "同步归约全行最大值",
        sourceEntityIds: ["logits", "row-owner"],
        targetEntityIds: ["row-max"],
        values: { "row-max": 1002 },
        result: "m = 1002",
        explanation: "所有 lane 先合成同一个行最大值，而不是各自使用局部最大值。",
      },
      {
        title: "减最大值并计算指数",
        sourceEntityIds: ["logits", "row-max"],
        targetEntityIds: ["shifted", "exponentials", "local-sum"],
        values: {
          shifted: [-2, -1, 0],
          exponentials: [0.1353, 0.3679, 1],
          "local-sum": [0.1353, 0.3679, 1],
        },
        outputEntityIds: ["shifted", "exponentials", "local-sum"],
        transfers: [
          { from: "logits", to: "shifted", payload: [1000, 1001, 1002], label: "读取原始 logits" },
          { from: "row-max", to: "shifted", payload: 1002, label: "每项减去统一行最大值" },
          { from: "shifted", to: "exponentials", payload: [-2, -1, 0], label: "对稳定移位值求指数" },
          { from: "exponentials", to: "local-sum", payload: [0.1353, 0.3679, 1], label: "保存各 lane 指数贡献" },
        ],
        result: "exp(x-m) ≈ [0.1353,0.3679,1]",
        explanation: "最大指数固定为 1，避免直接计算 exp(1002) 造成溢出。",
      },
      {
        title: "再次同步归约指数总和",
        sourceEntityIds: ["local-sum"],
        targetEntityIds: ["denominator"],
        values: { denominator: 1.5032 },
        result: "sum exp(x-m) ≈ 1.5032",
        explanation: "第二次全行归约得到所有 lane 共同使用的唯一分母。",
      },
      {
        title: "逐项相除并写回概率",
        sourceEntityIds: ["exponentials", "denominator"],
        targetEntityIds: ["probabilities", "probability-sum"],
        values: { probabilities: [0.09, 0.2447, 0.6652], "probability-sum": 0.9999 },
        outputEntityIds: ["probabilities", "probability-sum"],
        transfers: [
          { from: "exponentials", to: "probabilities", payload: [0.1353, 0.3679, 1], label: "三个指数值进入归一化" },
          { from: "denominator", to: "probabilities", payload: 1.5032, label: "每项除以同一分母" },
          { from: "probabilities", to: "probability-sum", payload: [0.09, 0.2447, 0.6652], label: "核对概率总和" },
        ],
        result: "p ≈ [0.0900,0.2447,0.6652]，sum(p) ≈ 1",
        explanation: "每个指数值除以同一分母，输出有限并在浮点误差内归一化。",
      },
    ],
  },
};
