import type { CudaStoryboardDefinition } from "./storyboard.ts";

export const reductionSceneDefinitions: Record<number, CudaStoryboardDefinition> = {
  202: {
    kind: "pipeline",
    ariaLabel: "有限负数输入经过线程 warp block 和 grid 四级极值归约",
    entities: [
      { id: "input", label: "候选 x", role: "input", initialValue: [-7, -2, -9, -4] },
      { id: "finite-check", label: "有限值检查", role: "control", initialValue: "unchecked" },
      { id: "registers", label: "线程寄存器", role: "intermediate", initialValue: ["empty", "empty", "empty", "empty"] },
      { id: "local-pairs", label: "线程局部 (min,max)", role: "intermediate", initialValue: "pending" },
      { id: "warp-pair", label: "warp 极值对", role: "intermediate", initialValue: "pending" },
      { id: "shared-pairs", label: "shared warp 结果", role: "intermediate", initialValue: "pending" },
      { id: "block-barrier-before", label: "块内屏障前态", role: "control", initialValue: "waiting" },
      { id: "block-barrier", label: "块内屏障", role: "control", initialValue: "waiting" },
      { id: "block-pair", label: "block 极值对", role: "intermediate", initialValue: "pending" },
      { id: "partials", label: "全局部分极值", role: "intermediate", initialValue: "pending" },
      { id: "grid-pair", label: "递归归约结果", role: "intermediate", initialValue: "pending" },
      { id: "output", label: "最终 (min,max)", role: "output", initialValue: "pending" },
    ],
    formulaEntityIds: [["input", "registers"], ["output"], ["output"], ["input"]],
    layout: {
      laneIds: ["全局内存", "线程与 warp", "block", "grid"],
      laneByEntityId: {
        input: "全局内存",
        "finite-check": "全局内存",
        registers: "线程与 warp",
        "local-pairs": "线程与 warp",
        "warp-pair": "线程与 warp",
        "shared-pairs": "block",
        "block-barrier-before": "block",
        "block-barrier": "block",
        "block-pair": "block",
        partials: "全局内存",
        "grid-pair": "grid",
        output: "全局内存",
      },
      stageEntityIds: [
        "input", "finite-check", "registers", "local-pairs", "warp-pair",
        "shared-pairs", "block-barrier-before", "block-barrier", "block-pair", "partials", "grid-pair", "output",
      ],
    },
    steps: [
      {
        title: "拒绝非有限候选值",
        sourceEntityIds: ["input"],
        targetEntityIds: ["finite-check"],
        values: { "finite-check": "4 / 4 finite" },
        result: "[-7, -2, -9, -4] 全部有限",
        explanation: "先固定 NaN 和 Inf 策略，后续 min/max 指令才有唯一语义。",
      },
      {
        title: "线程读取候选值",
        sourceEntityIds: ["input"],
        targetEntityIds: ["registers"],
        values: { registers: [-7, -2, -9, -4] },
        result: "寄存器候选 = [-7, -2, -9, -4]",
        explanation: "每个有效线程从连续全局地址取得一个负数候选。",
      },
      {
        title: "寄存器形成局部极值对",
        sourceEntityIds: ["registers"],
        targetEntityIds: ["local-pairs"],
        values: { "local-pairs": ["(-7,-2)", "(-9,-4)"] },
        result: "两组局部对 = [(-7,-2), (-9,-4)]",
        explanation: "每两个候选先比较一次，且最大值初值不是错误的 0。",
      },
      {
        title: "warp shuffle 合并极值",
        sourceEntityIds: ["local-pairs"],
        targetEntityIds: ["warp-pair"],
        values: { "warp-pair": [-9, -2] },
        result: "warp (min,max) = (-9,-2)",
        explanation: "lane 间交换局部对，并分别执行 min 和 max。",
      },
      {
        title: "lane 0 写 shared 极值对",
        sourceEntityIds: ["warp-pair", "block-barrier-before"],
        targetEntityIds: ["shared-pairs", "block-barrier"],
        values: { "shared-pairs": [[-9, -2]], "block-barrier": "released" },
        transfers: [
          { from: "warp-pair", to: "shared-pairs", payload: [-9, -2], label: "lane 0 发布 warp 极值对" },
          { from: "shared-pairs", to: "block-barrier", payload: [[-9, -2]], label: "shared 写入完成后到达屏障" },
          { from: "block-barrier-before", to: "block-barrier", payload: "waiting", label: "屏障从 waiting 变为 released" },
        ],
        result: "shared 中有 1 个有效 warp 对；barrier: waiting -> released",
        explanation: "lane 0 发布 warp 结果；块内屏障从 waiting 变为 released 后，第一个 warp 才能读取它。",
      },
      {
        title: "第一个 warp 合成 block 极值",
        sourceEntityIds: ["shared-pairs", "block-barrier"],
        targetEntityIds: ["block-pair"],
        values: { "block-pair": [-9, -2] },
        transfers: [
          { from: "shared-pairs", to: "block-pair", payload: [[-9, -2]], label: "读取唯一有效 warp 极值对" },
          { from: "block-barrier", to: "block-pair", payload: "released", label: "屏障放行 shared 读取" },
        ],
        result: "block (min,max) = (-9,-2)",
        explanation: "只有 shared 中标记为有效的 warp 对参与第二级 shuffle。",
      },
      {
        title: "写出 block 部分极值",
        sourceEntityIds: ["block-pair"],
        targetEntityIds: ["partials"],
        values: { partials: [[-9, -2]] },
        result: "全局部分量 = [(-9,-2)]",
        explanation: "block 结果进入全局数组，成为下一次 kernel 的输入。",
      },
      {
        title: "kernel 边界后递归归约",
        sourceEntityIds: ["partials"],
        targetEntityIds: ["grid-pair"],
        values: { "grid-pair": [-9, -2] },
        result: "grid 极值对 = (-9,-2)",
        explanation: "新 kernel 提供跨 block 的全局可见性，并继续同一种比较。",
      },
      {
        title: "写回唯一极值输出",
        sourceEntityIds: ["grid-pair"],
        targetEntityIds: ["output"],
        values: { output: [-9, -2] },
        result: "min = -9，max = -2",
        explanation: "全负输入仍正确得到 -2，而不会被错误哨兵 0 覆盖。",
      },
    ],
  },
  203: {
    kind: "pipeline",
    ariaLabel: "向量三四通过缩放平方和得到稳定 L2 范数五",
    entities: [
      { id: "input", label: "向量 x", role: "input", initialValue: [3, 4] },
      { id: "abs-local", label: "局部绝对值", role: "intermediate", initialValue: [0, 0] },
      { id: "scale-partial", label: "block 最大绝对值", role: "intermediate", initialValue: 0 },
      { id: "scale", label: "全局尺度 s", role: "intermediate", initialValue: 0 },
      { id: "scaled-square", label: "缩放平方贡献", role: "intermediate", initialValue: [0, 0] },
      { id: "q-partial", label: "block q 部分量", role: "intermediate", initialValue: 0 },
      { id: "q", label: "全局平方和 q", role: "intermediate", initialValue: 0 },
      { id: "norm", label: "L2 范数", role: "output", initialValue: 0 },
    ],
    formulaEntityIds: [["input"], ["scale"], ["scaled-square"], ["norm"]],
    layout: {
      laneIds: ["全局内存", "最大值 kernel", "平方和 kernel", "最终 kernel"],
      laneByEntityId: {
        input: "全局内存",
        "abs-local": "最大值 kernel",
        "scale-partial": "最大值 kernel",
        scale: "全局内存",
        "scaled-square": "平方和 kernel",
        "q-partial": "平方和 kernel",
        q: "全局内存",
        norm: "最终 kernel",
      },
      stageEntityIds: ["input", "abs-local", "scale-partial", "scale", "scaled-square", "q-partial", "q", "norm"],
    },
    steps: [
      {
        title: "读取向量并取绝对值",
        sourceEntityIds: ["input"],
        targetEntityIds: ["abs-local"],
        values: { "abs-local": [3, 4] },
        result: "|x| = [3, 4]",
        explanation: "最大值 kernel 首先形成不会受符号影响的候选尺度。",
      },
      {
        title: "块内归约最大绝对值",
        sourceEntityIds: ["abs-local"],
        targetEntityIds: ["scale-partial"],
        values: { "scale-partial": 4 },
        result: "block 最大绝对值 = 4",
        explanation: "warp 与 shared memory 分层合并，屏障保护跨 warp 的部分量。",
      },
      {
        title: "跨 kernel 得到全局尺度",
        sourceEntityIds: ["scale-partial"],
        targetEntityIds: ["scale"],
        values: { scale: 4 },
        result: "s = 4",
        explanation: "kernel 边界后全局最大值确定，所有分量将使用同一尺度。",
      },
      {
        title: "重新读取并计算缩放平方",
        sourceEntityIds: ["input", "scale"],
        targetEntityIds: ["scaled-square"],
        values: { "scaled-square": [0.5625, 1] },
        expression: "(x_i/4)^2",
        result: "贡献 = [0.5625, 1]",
        explanation: "先除以最大绝对值再平方，让中间量稳定地落在 0 到 1。",
      },
      {
        title: "块内合成 q 部分量",
        sourceEntityIds: ["scaled-square"],
        targetEntityIds: ["q-partial"],
        values: { "q-partial": 1.5625 },
        result: "block q = 1.5625",
        explanation: "平方贡献在第二个 kernel 中独立归约并写出 block 部分和。",
      },
      {
        title: "跨 block 归约全局 q",
        sourceEntityIds: ["q-partial"],
        targetEntityIds: ["q"],
        values: { q: 1.5625 },
        result: "q = 1.5625",
        explanation: "新的 kernel 边界使所有 q 部分量可见，再归约为一个标量。",
      },
      {
        title: "乘回尺度得到范数",
        sourceEntityIds: ["scale", "q"],
        targetEntityIds: ["norm"],
        values: { norm: 5 },
        expression: "4\\sqrt{1.5625}=5",
        result: "||x||_2 = 5",
        explanation: "最终线程计算 s 乘根号 q，恢复原向量的尺度。",
      },
    ],
  },
};
