import type { CudaStoryboardDefinition } from "./storyboard.ts";

export const stencilSceneDefinitions: Record<number, CudaStoryboardDefinition> = {
  501: {
    kind: "matrix",
    ariaLabel: "二乘二输入以 padding 1 和二乘二卷积核生成三乘三输出",
    entities: [
      { id: "input", label: "输入 X", role: "input", initialValue: [[1, 2], [3, 4]] },
      { id: "weights", label: "卷积核 W", role: "input", initialValue: [[1, 0], [0, -1]] },
      { id: "windows", label: "Implicit GEMM 窗口行", role: "intermediate", initialValue: "pending" },
      { id: "output-map", label: "输出坐标 (p,q)", role: "control", initialValue: "unmapped" },
      { id: "input-tile", label: "shared 输入 tile + halo", role: "intermediate", initialValue: "empty" },
      { id: "weight-tile", label: "shared 权重 tile", role: "intermediate", initialValue: "empty" },
      { id: "padding", label: "padding 槽位", role: "control", initialValue: "not needed" },
      { id: "barrier", label: "块内屏障", role: "control", initialValue: "waiting" },
      { id: "accumulator", label: "窗口乘加器", role: "intermediate", initialValue: [[0, 0, 0], [0, 0, 0], [0, 0, 0]] },
      { id: "channel-state", label: "通道 tile 状态", role: "control", initialValue: "channel 0 pending" },
      { id: "output", label: "输出 Y", role: "output", initialValue: [[0, 0, 0], [0, 0, 0], [0, 0, 0]] },
      { id: "shape", label: "R x S, stride, padding", role: "control", initialValue: "2x2, (1,1), (1,1)" },
    ],
    formulaEntityIds: [
      ["input", "input-tile"], ["weights", "weight-tile"], ["accumulator", "output"],
      ["shape", "windows"], ["shape", "output-map"], ["padding", "input-tile"],
    ],
    layout: {
      rows: 3,
      columns: 4,
      cellEntityIds: [
        ["input", "windows", "output-map", "output"],
        ["weights", "input-tile", "weight-tile", "accumulator"],
        ["shape", "padding", "barrier", "channel-state"],
      ],
    },
    steps: [
      {
        title: "把九个窗口映射为 GEMM 行",
        sourceEntityIds: ["input", "shape"],
        targetEntityIds: ["windows"],
        values: {
          windows: [
            [0, 0, 0, 1], [0, 0, 1, 2], [0, 0, 2, 0],
            [0, 1, 0, 3], [1, 2, 3, 4], [2, 0, 4, 0],
            [0, 3, 0, 0], [3, 4, 0, 0], [4, 0, 0, 0],
          ],
        },
        result: "九个 padding-1 窗口展平为九行；Implicit GEMM 不实际落盘",
        explanation: "输出位置对应窗口行，(r,s) 对应归约列，这就是卷积到 GEMM 的统一映射。",
      },
      {
        title: "线程块映射 3x3 输出 tile",
        sourceEntityIds: ["windows", "shape"],
        targetEntityIds: ["output-map"],
        values: { "output-map": [["(0,0)", "(0,1)", "(0,2)"], ["(1,0)", "(1,1)", "(1,2)"], ["(2,0)", "(2,1)", "(2,2)"]] },
        result: "九个线程分别负责 Y 的九个坐标",
        explanation: "stride=1、padding=1 时，边缘输出的窗口左上角落在原图范围之外。",
      },
      {
        title: "协作加载输入 halo 与权重",
        sourceEntityIds: ["input", "weights", "output-map"],
        targetEntityIds: ["input-tile", "weight-tile", "padding"],
        values: {
          "input-tile": [[0, 0, 0, 0], [0, 1, 2, 0], [0, 3, 4, 0], [0, 0, 0, 0]],
          "weight-tile": [[1, 0], [0, -1]],
          padding: "12 out-of-range slots -> 0",
        },
        outputEntityIds: ["input-tile", "weight-tile", "padding"],
        transfers: [
          { from: "input", to: "input-tile", payload: [1, 2, 3, 4], label: "四个有效输入装入 shared 中心" },
          { from: "weights", to: "weight-tile", payload: [1, 0, 0, -1], label: "四个核权重装入 shared" },
          { from: "output-map", to: "padding", payload: "12 out-of-range slots", label: "边缘输出坐标标记越界读取" },
        ],
        result: "4x4 shared tile 显式包含 12 个零 padding 槽位",
        explanation: "相邻窗口复用重叠像素；原图外的十二个槽位明确写零，边缘窗口因此可逐项核对。",
      },
      {
        title: "同步后展开窗口乘加",
        sourceEntityIds: ["input-tile", "weight-tile"],
        targetEntityIds: ["barrier", "accumulator"],
        values: { barrier: "released", accumulator: [[-1, -2, 0], [-3, -3, 2], [0, 3, 4]] },
        outputEntityIds: ["accumulator", "barrier"],
        transfers: [
          { from: "input-tile", to: "accumulator", payload: "nine padded 2x2 windows", label: "每个输出线程读取自己的补零窗口" },
          { from: "weight-tile", to: "accumulator", payload: [1, 0, 0, -1], label: "每个窗口应用同一卷积核" },
          { from: "input-tile", to: "barrier", payload: "4 valid + 12 padded slots ready", label: "完整 shared tile 到达屏障" },
        ],
        expression: "1X_{p,q}-X_{p+1,q+1}",
        result: "九个窗口累加器 = [[-1,-2,0],[-3,-3,2],[0,3,4]]",
        explanation: "共享 tile 完整后，每个线程读取自己的 2x2 补零窗口并乘以 [1,0;0,-1]。",
      },
      {
        title: "确认当前通道 tile 已读完",
        sourceEntityIds: ["accumulator", "input-tile"],
        targetEntityIds: ["channel-state"],
        values: { "channel-state": "channel 0 complete; shared reusable" },
        result: "唯一输入通道完成",
        explanation: "第二个屏障防止仍在读当前 tile 时被下一通道的数据覆盖。",
      },
      {
        title: "写回输出特征图",
        sourceEntityIds: ["accumulator"],
        targetEntityIds: ["output"],
        values: { output: [[-1, -2, 0], [-3, -3, 2], [0, 3, 4]] },
        result: "Y = [[-1,-2,0],[-3,-3,2],[0,3,4]]",
        explanation: "每个线程把自己的窗口累加值写回对应输出坐标。",
      },
    ],
  },
  502: {
    kind: "matrix",
    ariaLabel: "四乘四输入按二乘二窗口和步幅二执行最大池化",
    entities: [
      { id: "input", label: "输入 X", role: "input", initialValue: [[1, 5, 2, 4], [3, 0, 7, 6], [8, 2, 9, 1], [4, 3, 5, 0]] },
      { id: "window-shape", label: "窗口 R x S", role: "control", initialValue: "2x2" },
      { id: "stride", label: "步幅 (u,v)", role: "control", initialValue: [2, 2] },
      { id: "thread-map", label: "输出线程坐标", role: "control", initialValue: "unmapped" },
      { id: "windows", label: "四个读取窗口", role: "intermediate", initialValue: "pending" },
      { id: "running-max", label: "线程 running max", role: "intermediate", initialValue: ["-inf", "-inf", "-inf", "-inf"] },
      { id: "bounds", label: "边界检查", role: "control", initialValue: "unchecked" },
      { id: "output", label: "池化输出 Y", role: "output", initialValue: [[0, 0], [0, 0]] },
    ],
    formulaEntityIds: [["input", "windows"], ["window-shape", "windows"], ["running-max", "output"], ["stride", "thread-map"]],
    layout: {
      rows: 2,
      columns: 4,
      cellEntityIds: [
        ["input", "thread-map", "windows", "running-max"],
        ["window-shape", "stride", "bounds", "output"],
      ],
    },
    steps: [
      {
        title: "线程映射四个输出窗口",
        sourceEntityIds: ["input", "stride"],
        targetEntityIds: ["thread-map", "bounds"],
        values: {
          "thread-map": [["(0,0)", "(0,1)"], ["(1,0)", "(1,1)"]],
          bounds: "4 / 4 windows valid",
        },
        transfers: [
          { from: "input", to: "thread-map", payload: [[1, 5, 2, 4], [3, 0, 7, 6], [8, 2, 9, 1], [4, 3, 5, 0]], label: "输入形状确定 2x2 输出网格" },
          { from: "stride", to: "thread-map", payload: [2, 2], label: "stride=2 映射四个窗口左上角" },
          { from: "input", to: "bounds", payload: [[1, 5, 2, 4], [3, 0, 7, 6], [8, 2, 9, 1], [4, 3, 5, 0]], label: "4x4 输入容纳四个完整窗口" },
          { from: "stride", to: "bounds", payload: [2, 2], label: "步幅检查确认所有窗口有效" },
        ],
        result: "输出线程覆盖 2x2 网格",
        explanation: "每个线程用输出坐标乘 stride=2，得到互不重叠窗口的左上角。",
      },
      {
        title: "读取每个 2x2 窗口",
        sourceEntityIds: ["input", "thread-map", "window-shape", "bounds"],
        targetEntityIds: ["windows"],
        values: { windows: [[1, 5, 3, 0], [2, 4, 7, 6], [8, 2, 4, 3], [9, 1, 5, 0]] },
        result: "窗口 = [[1,5,3,0], [2,4,7,6], [8,2,4,3], [9,1,5,0]]",
        explanation: "每个线程独立读取自己的四个候选，无需与其他线程共享中间值。",
      },
      {
        title: "线程内比较全部候选",
        sourceEntityIds: ["windows"],
        targetEntityIds: ["running-max"],
        values: { "running-max": [5, 7, 8, 9] },
        result: "四个窗口最大值 = [5, 7, 8, 9]",
        explanation: "running max 完全保存在寄存器里，所以不需要块内同步。",
      },
      {
        title: "边界检查后写回",
        sourceEntityIds: ["running-max", "thread-map", "bounds"],
        targetEntityIds: ["output"],
        values: { output: [[5, 7], [8, 9]] },
        transfers: [
          { from: "running-max", to: "output", payload: [5, 7, 8, 9], label: "四个最大值写回对应坐标" },
          { from: "thread-map", to: "output", payload: [["(0,0)", "(0,1)"], ["(1,0)", "(1,1)"]], label: "最大值写回对应输出坐标" },
          { from: "bounds", to: "output", payload: "4 / 4 windows valid", label: "边界检查结果放行四个写回" },
        ],
        result: "Y = [[5,7],[8,9]]",
        explanation: "valid pooling 的四个窗口都在范围内，各线程恰好写一个输出。",
      },
    ],
  },
  503: {
    kind: "matrix",
    ariaLabel: "左上角脉冲图像以 clamp halo 经过横向和纵向一维高斯卷积",
    entities: [
      { id: "input", label: "左上角脉冲 X", role: "input", initialValue: [[1, 0, 0], [0, 0, 0], [0, 0, 0]] },
      { id: "weights", label: "一维权重 g", role: "input", initialValue: [0.25, 0.5, 0.25] },
      { id: "kernel-2d", label: "等价二维核 G", role: "intermediate", initialValue: "pending" },
      { id: "horizontal-tile", label: "横向 shared tile + halo", role: "intermediate", initialValue: "empty" },
      { id: "horizontal-barrier", label: "横向屏障", role: "control", initialValue: "waiting" },
      { id: "horizontal-register", label: "横向寄存器结果", role: "intermediate", initialValue: "pending" },
      { id: "temporary", label: "全局临时 H", role: "intermediate", initialValue: [[0, 0, 0], [0, 0, 0], [0, 0, 0]] },
      { id: "kernel-boundary", label: "kernel 全局边界", role: "control", initialValue: "waiting" },
      { id: "vertical-tile", label: "纵向 shared tile + halo", role: "intermediate", initialValue: "empty" },
      { id: "vertical-barrier", label: "纵向屏障", role: "control", initialValue: "waiting" },
      { id: "output", label: "模糊输出 Y", role: "output", initialValue: [[0, 0, 0], [0, 0, 0], [0, 0, 0]] },
      { id: "image-shape", label: "图像 H_img x W_img", role: "control", initialValue: "3x3" },
    ],
    formulaEntityIds: [
      ["input", "horizontal-tile", "vertical-tile"], ["kernel-2d"], ["weights"],
      ["horizontal-tile", "vertical-tile"], ["image-shape"], ["temporary"], ["output"],
    ],
    layout: {
      rows: 3,
      columns: 4,
      cellEntityIds: [
        ["input", "horizontal-tile", "horizontal-register", "temporary"],
        ["weights", "horizontal-barrier", "kernel-boundary", "image-shape"],
        ["kernel-2d", "vertical-tile", "vertical-barrier", "output"],
      ],
    },
    steps: [
      {
        title: "加载横向 tile 与 clamp halo",
        sourceEntityIds: ["input", "image-shape"],
        targetEntityIds: ["horizontal-tile"],
        values: { "horizontal-tile": [[1, 1, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0]] },
        result: "左 halo 重复非零边缘值 1，右 halo 重复 0",
        explanation: "每行两端额外装载一个 clamp-to-edge halo，避免卷积时越界。",
      },
      {
        title: "广播权重并执行横向卷积",
        sourceEntityIds: ["horizontal-tile", "weights"],
        targetEntityIds: ["horizontal-barrier", "horizontal-register", "kernel-2d"],
        values: {
          "horizontal-barrier": "released",
          "horizontal-register": [[0.75, 0.25, 0], [0, 0, 0], [0, 0, 0]],
          "kernel-2d": [[0.0625, 0.125, 0.0625], [0.125, 0.25, 0.125], [0.0625, 0.125, 0.0625]],
        },
        outputEntityIds: ["horizontal-barrier", "horizontal-register", "kernel-2d"],
        transfers: [
          { from: "horizontal-tile", to: "horizontal-register", payload: [1, 1, 0, 0, 0], label: "首行 clamp tile 进入横向卷积" },
          { from: "weights", to: "horizontal-register", payload: [0.25, 0.5, 0.25], label: "广播一维权重" },
          { from: "weights", to: "kernel-2d", payload: [0.25, 0.5, 0.25], label: "外积形成等价二维核" },
          { from: "horizontal-tile", to: "horizontal-barrier", payload: "tile ready", label: "横向 tile 写入完成" },
        ],
        result: "横向角落响应首行为 [0.75, 0.25, 0]",
        explanation: "constant memory 广播 g；屏障后每个像素沿行读取三个 shared 值。",
      },
      {
        title: "横向结果写入独立临时缓冲",
        sourceEntityIds: ["horizontal-register"],
        targetEntityIds: ["temporary"],
        values: { temporary: [[0.75, 0.25, 0], [0, 0, 0], [0, 0, 0]] },
        result: "H = [[0.75,0.25,0],[0,0,0],[0,0,0]]",
        explanation: "独立 H 缓冲保留完整横向输出，不会覆盖仍可能被读取的原图。",
      },
      {
        title: "横向 kernel 结束形成全局边界",
        sourceEntityIds: ["temporary"],
        targetEntityIds: ["kernel-boundary"],
        values: { "kernel-boundary": "H globally visible" },
        result: "纵向 kernel 可以读取完整 H",
        explanation: "块内屏障不能同步整个 grid，kernel 边界负责跨 block 发布临时结果。",
      },
      {
        title: "纵向重新加载 H 与 clamp halo",
        sourceEntityIds: ["temporary", "kernel-boundary"],
        targetEntityIds: ["vertical-tile"],
        values: { "vertical-tile": [[0.75, 0.25, 0], [0.75, 0.25, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0]] },
        result: "顶部 halo 重复 H 的非零首行，底部重复零末行",
        explanation: "第二个 kernel 改为按列复用 H，并对顶部和底部采用同一 clamp 规则。",
      },
      {
        title: "同步后纵向卷积并写回",
        sourceEntityIds: ["vertical-tile", "weights"],
        targetEntityIds: ["vertical-barrier", "output"],
        values: {
          "vertical-barrier": "released",
          output: [[0.5625, 0.1875, 0], [0.1875, 0.0625, 0], [0, 0, 0]],
        },
        outputEntityIds: ["output", "vertical-barrier"],
        transfers: [
          { from: "vertical-tile", to: "output", payload: "clamped 5x3 tile", label: "纵向窗口进入最终卷积" },
          { from: "weights", to: "output", payload: [0.25, 0.5, 0.25], label: "广播纵向一维权重" },
          { from: "vertical-tile", to: "vertical-barrier", payload: "tile ready", label: "纵向 tile 写入完成" },
        ],
        result: "Y 左上角为 0.5625；零 padding 时只会是 0.25",
        explanation: "纵向卷积再次重复顶部边缘，因此角落响应明确体现 clamp-to-edge，而不是零 padding。",
      },
    ],
  },
};
