import {
  check,
  connection,
  entity,
  transfer,
  type ConceptFrameProfile,
  type ConceptSceneProfileTable,
} from "./profile.ts";

function frames(stages: Array<{
  sources: string[];
  targets: string[];
  values?: ConceptFrameProfile["values"];
  connections?: string[];
  transfers?: ConceptFrameProfile["transfers"];
  result: string;
  check: ReturnType<typeof check>;
  checks?: ReturnType<typeof check>[];
  inputs?: string[];
  outputs?: string[];
  metrics?: string[];
  expression?: string;
}>): ConceptFrameProfile[] {
  return stages.map((stage) => ({
    sourceEntityIds: stage.sources,
    targetEntityIds: stage.targets,
    values: stage.values ?? {},
    visibleConnectionIds: stage.connections ?? [],
    transfers: stage.transfers ?? [],
    result: stage.result,
    check: stage.check,
    checks: stage.checks,
    inputEntityIds: stage.inputs,
    outputEntityIds: stage.outputs,
    metricEntityIds: stage.metrics,
    expression: stage.expression,
  }));
}

export const computerArchitectureSceneProfiles = {
  40031: {
    kind: "array",
    entities: [
      entity("assembly", "汇编指令", "input", "addi x5,x6,8"),
      entity("operands", "解析操作数", "intermediate", [], 0),
      entity("format", "RISC-V I 型格式", "intermediate", "unknown", 1),
      entity("opcode-width", "opcode [6:0] 位宽", "intermediate", 0, 1),
      entity("opcode-bits", "opcode [6:0]", "intermediate", "pending", 1),
      entity("funct3-bits", "funct3 [14:12]", "intermediate", "pending", 1),
      entity("rd-width", "rd [11:7] 位宽", "intermediate", 0, 2),
      entity("funct3-width", "funct3 [14:12] 位宽", "intermediate", 0, 2),
      entity("rs1-width", "rs1 [19:15] 位宽", "intermediate", 0, 2),
      entity("immediate-width", "imm [31:20] 位宽", "intermediate", 0, 2),
      entity("rd-bits", "rd=x5 [11:7]", "intermediate", "pending", 2),
      entity("rs1-bits", "rs1=x6 [19:15]", "intermediate", "pending", 2),
      entity("immediate-bits", "imm=8 [31:20]", "intermediate", "pending", 2),
      entity("word-width", "机器字位宽", "output", 0, 3),
      entity("machine-word-bits", "32 位机器字 W", "output", "pending", 3),
      entity("machine-word-hex", "机器字十六进制", "output", "pending", 3),
      entity("machine-word-value", "机器字无符号值", "output", 0, 3),
      entity("decoded-fields", "反解位段", "intermediate", [], 4),
      entity("decoded", "反解指令", "output", "pending", 4),
    ],
    connections: [
      connection("assembly-operands", "assembly", "operands"),
      connection("assembly-format", "assembly", "format"),
      connection("format-opcode-width", "format", "opcode-width"),
      connection("format-opcode-bits", "format", "opcode-bits"),
      connection("format-funct3-bits", "format", "funct3-bits"),
      connection("operands-rd", "operands", "rd-bits"),
      connection("operands-rs1", "operands", "rs1-bits"),
      connection("operands-imm", "operands", "immediate-bits"),
      connection("format-rd-width", "format", "rd-width"),
      connection("format-funct3-width", "format", "funct3-width"),
      connection("format-rs1-width", "format", "rs1-width"),
      connection("format-imm-width", "format", "immediate-width"),
      connection("opcode-word", "opcode-bits", "machine-word-bits"),
      connection("rd-word", "rd-bits", "machine-word-bits"),
      connection("funct3-word", "funct3-bits", "machine-word-bits"),
      connection("rs1-word", "rs1-bits", "machine-word-bits"),
      connection("imm-word", "immediate-bits", "machine-word-bits"),
      connection("word-fields", "machine-word-bits", "decoded-fields"),
      connection("fields-decoded", "decoded-fields", "decoded"),
    ],
    formulaBindings: {
      W: ["machine-word-bits"],
      "w_{\\mathrm{op}}": ["opcode-bits"],
      "w_{\\mathrm{rd}}": ["rd-bits"],
      "w_{\\mathrm{funct3}}": ["funct3-bits"],
      "w_{\\mathrm{rs1}}": ["rs1-bits"],
      "w_{\\mathrm{imm}}": ["immediate-bits"],
    },
    frames: frames([
      {
        sources: ["assembly"], targets: ["operands"],
        values: { operands: ["rd=x5", "rs1=x6", "imm=8"] },
        connections: ["assembly-operands"],
        transfers: [transfer("parse-addi", "assembly", "operands", "addi x5,x6,8", "解析助记符和操作数")],
        result: "解析 addi，得到 rd=x5、rs1=x6、imm=8",
        check: check("operands", ["rd=x5", "rs1=x6", "imm=8"], "addi 不含 rs2"),
      },
      {
        sources: ["assembly", "operands"],
        targets: ["format", "opcode-width", "opcode-bits", "funct3-bits"],
        values: { format: "I-type", "opcode-width": 7, "opcode-bits": "0010011", "funct3-bits": "000" },
        connections: ["assembly-format", "format-opcode-width", "format-opcode-bits", "format-funct3-bits"],
        transfers: [transfer("select-i-type", "assembly", "format", "addi x5,x6,8", "由 addi 选择 I 型")],
        result: "addi 选择 I 型；opcode[6:0]=0010011，funct3[14:12]=000",
        check: check("opcode-bits", "0010011", "addi 操作码为 0010011"),
        checks: [check("funct3-bits", "000", "addi 的 funct3 为 000")],
        expression: "w_{\\mathrm{op}}=0010011,\\quad w_{\\mathrm{funct3}}=000",
      },
      {
        sources: ["format", "operands"],
        targets: ["rd-width", "funct3-width", "rs1-width", "immediate-width", "rd-bits", "rs1-bits", "immediate-bits"],
        values: {
          "rd-width": 5, "funct3-width": 3, "rs1-width": 5, "immediate-width": 12,
          "rd-bits": "00101", "rs1-bits": "00110", "immediate-bits": "000000001000",
        },
        connections: ["format-rd-width", "format-funct3-width", "format-rs1-width", "format-imm-width", "operands-rd", "operands-rs1", "operands-imm"],
        transfers: [
          transfer("encode-rd", "operands", "rd-bits", ["rd=x5", "rs1=x6", "imm=8"], "x5 编为 00101"),
          transfer("encode-rs1", "operands", "rs1-bits", ["rd=x5", "rs1=x6", "imm=8"], "x6 编为 00110"),
          transfer("encode-imm", "operands", "immediate-bits", ["rd=x5", "rs1=x6", "imm=8"], "8 编为 12 位 000000001000"),
        ],
        result: "rd=x5 -> 00101；rs1=x6 -> 00110；imm=8 -> 000000001000",
        check: check("rd-bits", "00101", "rd 位段编码 x5"),
        checks: [check("rs1-bits", "00110", "rs1 位段编码 x6"), check("immediate-bits", "000000001000", "立即数按 12 位编码")],
        expression: "5_{10}=00101_2,\\quad 6_{10}=00110_2,\\quad 8_{10}=000000001000_2",
      },
      {
        sources: ["immediate-bits", "rs1-bits", "funct3-bits", "rd-bits", "opcode-bits"],
        targets: ["word-width", "machine-word-bits", "machine-word-hex", "machine-word-value"],
        values: {
          "word-width": 32,
          "machine-word-bits": "00000000100000110000001010010011",
          "machine-word-hex": "0x00830293",
          "machine-word-value": 8585875,
        },
        connections: ["opcode-word", "rd-word", "funct3-word", "rs1-word", "imm-word"],
        transfers: [
          transfer("imm-part", "immediate-bits", "machine-word-bits", "000000001000", "写入 [31:20]"),
          transfer("rs1-part", "rs1-bits", "machine-word-bits", "00110", "写入 [19:15]"),
          transfer("funct3-part", "funct3-bits", "machine-word-bits", "000", "写入 [14:12]"),
          transfer("rd-part", "rd-bits", "machine-word-bits", "00101", "写入 [11:7]"),
          transfer("opcode-part", "opcode-bits", "machine-word-bits", "0010011", "写入 [6:0]"),
        ],
        result: "按 [31:20|19:15|14:12|11:7|6:0] 拼成 0x00830293",
        check: check("machine-word-bits", "00000000100000110000001010010011", "机器字恰为 32 位"),
        checks: [check("machine-word-hex", "0x00830293", "十六进制结果可复算"), check("word-width", 32, "位段总宽度为 32")],
        expression: "000000001000\\Vert00110\\Vert000\\Vert00101\\Vert0010011=\\mathtt{0x00830293}",
      },
      {
        sources: ["machine-word-bits"], targets: ["decoded-fields", "decoded"],
        values: {
          "decoded-fields": ["imm=8", "rs1=x6", "funct3=000", "rd=x5", "opcode=0010011"],
          decoded: "addi x5,x6,8",
        },
        connections: ["word-fields", "fields-decoded"],
        transfers: [transfer("split-word", "machine-word-bits", "decoded-fields", "00000000100000110000001010010011", "按 I 型边界切回五个位段")],
        result: "反解得到 opcode=0010011、rd=x5、rs1=x6、imm=8，回到原指令",
        check: check("decoded", "addi x5,x6,8", "编码往返一致"),
        checks: [check("decoded-fields", ["imm=8", "rs1=x6", "funct3=000", "rd=x5", "opcode=0010011"], "五个位段均反解一致"), check("machine-word-hex", "0x00830293", "反解使用同一机器字")],
        expression: "\\mathtt{0x00830293}\\longrightarrow\\mathrm{addi\\ x5,x6,8}",
      },
    ]),
    explanations: [
      "先把汇编文本拆成助记符、目的寄存器、源寄存器和立即数；addi 没有 rs2。",
      "助记符同时确定 I 型布局、7 位 opcode=0010011 和 funct3=000。",
      "把寄存器编号和立即数分别补齐到 5、5、12 位，前导零也属于编码。",
      "严格按高位到低位的 I 型边界拼接五段，得到完整 32 位机器字和 0x00830293。",
      "再按同一边界切开机器字并反查 opcode，所有操作数都回到 addi x5,x6,8。",
    ],
  },
  40032: {
    kind: "pipeline",
    entities: [
      entity("instructions", "指令序列", "input", ["I1:lw x1,0(x2)", "I2:add x3,x1,x4"]),
      entity("stage-count", "流水级数 k", "input", 5), entity("instruction-count", "指令数 n", "input", 2),
      entity("cycle-state", "逐周期占用", "intermediate", [], 0), entity("dependency", "数据相关", "control", "none", 2),
      entity("bubble-count", "气泡数 b", "intermediate", 0, 3), entity("load-result", "I1 产生的 x1", "intermediate", "pending", 4),
      entity("forwarded-value", "转发值 x1", "intermediate", "pending", 4),
      entity("actual-cycles", "实际周期 C", "output", 0, 5), entity("speedup", "加速比 S", "output", 0, 5),
    ],
    connections: [connection("instructions-cycles", "instructions", "cycle-state"), connection("cycles-dependency", "cycle-state", "dependency"), connection("dependency-bubble", "dependency", "bubble-count"), connection("load-forward", "load-result", "forwarded-value"), connection("cycles-actual", "cycle-state", "actual-cycles"), connection("actual-speedup", "actual-cycles", "speedup")],
    formulaBindings: { n: ["instruction-count"], k: ["stage-count"], b: ["bubble-count"], "C_{\\mathrm{actual}}": ["actual-cycles"], S: ["speedup"] },
    frames: frames([
      { sources: ["instructions", "instruction-count"], targets: ["cycle-state"], values: { "cycle-state": ["c1:I1=IF"] }, connections: ["instructions-cycles"], transfers: [transfer("issue-i1", "instructions", "cycle-state", ["I1:lw x1,0(x2)", "I2:add x3,x1,x4"], "I1 进入取指")], result: "周期 1：I1=IF", check: check("cycle-state", ["c1:I1=IF"], "首条指令已进入流水线") },
      { sources: ["instructions", "cycle-state"], targets: ["cycle-state"], values: { "cycle-state": ["c2:I1=ID", "c2:I2=IF"] }, connections: ["instructions-cycles"], transfers: [transfer("issue-i2", "instructions", "cycle-state", ["I1:lw x1,0(x2)", "I2:add x3,x1,x4"], "I2 与 I1 重叠")], result: "周期 2：I1=ID，I2=IF", check: check("cycle-state", ["c2:I1=ID", "c2:I2=IF"], "两条指令重叠") },
      { sources: ["cycle-state", "instructions"], targets: ["dependency", "cycle-state"], values: { dependency: "I2 reads I1.x1", "cycle-state": ["c3:I1=EX", "c3:I2=ID"] }, connections: ["cycles-dependency"], transfers: [], result: "周期 3 检测 load-use 相关", check: check("dependency", "I2 reads I1.x1", "相关寄存器为 x1") },
      { sources: ["dependency", "cycle-state"], targets: ["bubble-count", "cycle-state"], values: { "bubble-count": 1, "cycle-state": ["c4:I1=MEM", "c4:I2=ID(stall)", "c4:EX=bubble"] }, connections: ["dependency-bubble"], transfers: [transfer("insert-bubble", "dependency", "bubble-count", "I2 reads I1.x1", "停顿一拍")], result: "周期 4 插入一个气泡", check: check("bubble-count", 1, "恰好一个 load-use 气泡") },
      { sources: ["load-result", "bubble-count", "cycle-state"], targets: ["load-result", "forwarded-value", "cycle-state"], values: { "load-result": "x1", "forwarded-value": "x1", "cycle-state": ["c5:I1=WB", "c5:I2=EX"] }, connections: ["load-forward"], transfers: [transfer("forward-x1", "load-result", "forwarded-value", "x1", "I1 把 x1 转发给 I2")], result: "周期 5 转发 x1 给 I2", check: check("forwarded-value", "x1", "I2 获取新 x1") },
      { sources: ["instructions", "cycle-state", "stage-count", "instruction-count", "bubble-count"], targets: ["cycle-state", "actual-cycles", "speedup"], values: { "cycle-state": ["c6:I2=MEM", "c7:I2=WB"], "actual-cycles": 7, speedup: 1.428571 }, connections: ["instructions-cycles", "cycles-actual", "actual-speedup"], transfers: [transfer("finish-pipeline", "instructions", "cycle-state", ["I1:lw x1,0(x2)", "I2:add x3,x1,x4"], "推进到 I2 写回")], result: "C=5+2-1+1=7，S=10/7", check: check("actual-cycles", 7, "实际周期为 7"), checks: [check("bubble-count", 1, "气泡计入总周期"), check("speedup", 1.428571, "加速比约为 10/7", "approx") ] },
    ]),
    explanations: ["I1 在周期 1 进入五级流水线。", "周期 2 时 I1 译码、I2 取指，形成重叠。", "I2 在译码阶段发现依赖 I1 的 x1。", "load-use 冒险使 I2 停一拍并插入一个气泡。", "周期 5 I1 写回，显式转发 x1 给 I2。", "I2 在周期 7 写回，总周期包含一个气泡。"],
  },
  40033: {
    kind: "pipeline",
    entities: [
      entity("address", "写地址", "input", "0x1374"), entity("request-tag", "请求 tag", "intermediate", "unknown"),
      entity("set-index", "组号", "intermediate", 0), entity("byte-offset", "块内偏移", "intermediate", 0),
      entity("write-value", "待写数据", "input", "0xA5"), entity("l1-tags", "L1 目标组有效 tag", "input", ["0x08", "0x0A"], 1),
      entity("l1-way1-valid", "way 1 原 valid", "input", true, 1), entity("l1-way1-tag", "way 1 原 tag", "input", "0x0A", 1),
      entity("l1-way1-data", "way 1 原数据", "input", "旧块(tag=0x0A)", 1), entity("l1-way1-dirty", "way 1 原 dirty", "input", true, 1),
      entity("replacement-way", "LRU 替换候选", "control", 1, 1), entity("l1-hit", "L1 命中", "control", "unknown", 1),
      entity("l2-hit", "L2 命中", "control", "unknown", 2), entity("cache-block", "L2 返回数据块", "intermediate", "pending", 3),
      entity("write-policy", "写策略", "control", "write-back + write-allocate", 4),
      entity("victim-way", "被替换 way", "intermediate", -1, 4), entity("victim-valid", "victim valid", "intermediate", false, 4),
      entity("victim-tag", "victim tag", "intermediate", "unknown", 4), entity("victim-data", "victim data", "intermediate", "pending", 4),
      entity("victim-dirty", "victim dirty", "intermediate", false, 4), entity("dirty-action", "脏行与写策略动作", "output", "pending", 4),
      entity("line-valid-after", "新行 valid", "output", false, 4), entity("line-tag-after", "新行 tag", "output", "unknown", 4),
      entity("line-data-after", "新行 data", "output", "pending", 4), entity("line-dirty-after", "新行 dirty", "output", false, 4),
      entity("l1-time", "tL1", "input", 1), entity("l1-miss-rate", "mL1", "input", 0.1), entity("l2-time", "tL2", "input", 4),
      entity("l2-miss-rate", "mL2", "input", 0.05), entity("memory-time", "tmem", "input", 200), entity("average-time", "平均访问时间", "output", 0, 4),
    ],
    connections: [
      connection("address-tag", "address", "request-tag"), connection("address-set", "address", "set-index"), connection("address-offset", "address", "byte-offset"),
      connection("set-l1", "set-index", "l1-hit"), connection("tags-l1", "l1-tags", "l1-hit"), connection("l1-l2", "l1-hit", "l2-hit"), connection("l2-block", "l2-hit", "cache-block"),
      connection("replacement-victim", "replacement-way", "victim-way"), connection("valid-victim", "l1-way1-valid", "victim-valid"),
      connection("tag-victim", "l1-way1-tag", "victim-tag"), connection("data-victim", "l1-way1-data", "victim-data"),
      connection("dirty-victim", "l1-way1-dirty", "victim-dirty"), connection("victim-writeback", "victim-dirty", "dirty-action"),
      connection("policy-action", "write-policy", "dirty-action"), connection("block-new-data", "cache-block", "line-data-after"),
      connection("write-new-data", "write-value", "line-data-after"), connection("offset-new-data", "byte-offset", "line-data-after"),
      connection("tag-new-tag", "request-tag", "line-tag-after"),
      connection("policy-new-valid", "write-policy", "line-valid-after"), connection("policy-new-dirty", "write-policy", "line-dirty-after"),
      connection("l1time-average", "l1-time", "average-time"), connection("l1miss-average", "l1-miss-rate", "average-time"),
      connection("l2time-average", "l2-time", "average-time"), connection("l2miss-average", "l2-miss-rate", "average-time"), connection("memtime-average", "memory-time", "average-time"),
    ],
    formulaBindings: { "t_{L1},t_{L2}": ["l1-time", "l2-time"], "m_{L1},m_{L2}": ["l1-miss-rate", "l2-miss-rate"], "t_{\\mathrm{mem}}": ["memory-time"], "T_{\\mathrm{avg}}": ["average-time"] },
    frames: frames([
      { sources: ["address"], targets: ["request-tag", "set-index", "byte-offset"], values: { "request-tag": "0x09", "set-index": 5, "byte-offset": 52 }, connections: ["address-tag", "address-set", "address-offset"], transfers: [transfer("decode-tag", "address", "request-tag", "0x1374", "提取 tag"), transfer("decode-set", "address", "set-index", "0x1374", "提取组索引"), transfer("decode-offset", "address", "byte-offset", "0x1374", "提取块内偏移")], result: "0x1374 拆为 tag=0x09、组 5、偏移 52", check: check("set-index", 5, "组索引为 5"), checks: [check("request-tag", "0x09", "请求 tag 为 0x09"), check("byte-offset", 52, "块内偏移为 52") ] },
      { sources: ["set-index", "request-tag", "l1-tags", "l1-way1-valid", "l1-way1-tag", "l1-way1-dirty"], targets: ["l1-hit"], values: { "l1-hit": false }, connections: ["set-l1", "tags-l1"], transfers: [transfer("compare-l1-tags", "l1-tags", "l1-hit", ["0x08", "0x0A"], "并行比较两路有效 tag")], result: "请求 tag=0x09，与组 5 的 0x08、0x0A 均不匹配", check: check("l1-hit", false, "L1 未命中") },
      { sources: ["l1-hit", "address"], targets: ["l2-hit"], values: { "l2-hit": true }, connections: ["l1-l2"], transfers: [transfer("lookup-l2", "l1-hit", "l2-hit", false, "L1 miss 后访问 L2")], result: "L2 找到相同 tag", check: check("l2-hit", true, "L2 命中") },
      { sources: ["l2-hit", "address"], targets: ["cache-block"], values: { "cache-block": "L2 块 0x1340..0x137F（64B）" }, connections: ["l2-block"], transfers: [transfer("fetch-cache-line", "l2-hit", "cache-block", true, "L2 返回完整 64B 块")], result: "从 L2 取回 0x1340..0x137F 的完整 64B 块", check: check("cache-block", "L2 块 0x1340..0x137F（64B）", "完整缓存行已到达") },
      {
        sources: [
          "replacement-way", "l1-way1-valid", "l1-way1-tag", "l1-way1-data",
          "l1-way1-dirty", "cache-block", "request-tag", "byte-offset",
          "write-value", "write-policy", "l1-time", "l1-miss-rate",
          "l2-time", "l2-miss-rate", "memory-time",
        ],
        targets: [
          "victim-way", "victim-valid", "victim-tag", "victim-data",
          "victim-dirty", "dirty-action", "line-valid-after", "line-tag-after",
          "line-data-after", "line-dirty-after", "average-time",
        ],
        values: {
          "victim-way": 1,
          "victim-valid": true,
          "victim-tag": "0x0A",
          "victim-data": "旧块(tag=0x0A)",
          "victim-dirty": true,
          "dirty-action": "写回脏 victim，再按 write-back 标脏新行",
          "line-valid-after": true,
          "line-tag-after": "0x09",
          "line-data-after": "L2 块 0x1340..0x137F；byte[52]=0xA5",
          "line-dirty-after": true,
          "average-time": 2.4,
        },
        connections: [
          "replacement-victim", "valid-victim", "tag-victim", "data-victim",
          "dirty-victim", "victim-writeback", "policy-action", "block-new-data",
          "write-new-data", "offset-new-data", "tag-new-tag", "policy-new-valid", "policy-new-dirty",
          "l1time-average", "l1miss-average", "l2time-average",
          "l2miss-average", "memtime-average",
        ],
        transfers: [
          transfer("select-lru-way", "replacement-way", "victim-way", 1, "LRU 选择 way 1"),
          transfer("snapshot-victim-valid", "l1-way1-valid", "victim-valid", true, "读取 victim valid"),
          transfer("snapshot-victim-tag", "l1-way1-tag", "victim-tag", "0x0A", "读取 victim tag"),
          transfer("snapshot-victim-data", "l1-way1-data", "victim-data", "旧块(tag=0x0A)", "读取 victim data"),
          transfer("snapshot-victim-dirty", "l1-way1-dirty", "victim-dirty", true, "读取 victim dirty"),
          transfer("write-back-victim", "victim-dirty", "dirty-action", true, "dirty=1，替换前写回旧块"),
          transfer("policy-to-action", "write-policy", "dirty-action", "write-back + write-allocate", "应用写回与写分配策略"),
          transfer("install-l2-block", "cache-block", "line-data-after", "L2 块 0x1340..0x137F（64B）", "write-allocate 安装整行"),
          transfer("write-request-byte", "write-value", "line-data-after", "0xA5", "在偏移 52 写入 0xA5"),
          transfer("install-request-tag", "request-tag", "line-tag-after", "0x09", "安装请求 tag"),
          transfer("validate-new-line", "write-policy", "line-valid-after", "write-back + write-allocate", "新缓存行置 valid=1"),
          transfer("apply-write-policy", "write-policy", "line-dirty-after", "write-back + write-allocate", "write-back 令新行 dirty=1"),
        ],
        result: "way 1 的脏旧块先写回；安装 tag=0x09 的 64B 块，写 byte[52]=0xA5，并将新行置 valid=1、dirty=1；Tavg=2.4ns",
        check: check("line-data-after", "L2 块 0x1340..0x137F；byte[52]=0xA5", "新缓存行包含本次写入"),
        checks: [
          check("victim-dirty", true, "脏 victim 触发写回"),
          check("line-valid-after", true, "新行有效"),
          check("line-tag-after", "0x09", "新行 tag 匹配请求"),
          check("line-dirty-after", true, "write-back 新行已标脏"),
          check("average-time", 2.4, "平均访问时间为 2.4ns"),
        ],
        outputs: [
          "victim-way", "victim-valid", "victim-tag", "victim-data",
          "victim-dirty", "dirty-action", "line-valid-after", "line-tag-after",
          "line-data-after", "line-dirty-after",
        ],
        metrics: ["average-time"],
      },
    ]),
    explanations: ["64B 缓存行、8 组的示例中，地址 0x1374 拆成 tag=0x09、组 5 和块内偏移 52。", "目标组两路都有效，但 tag 0x08、0x0A 均不等于请求 tag 0x09，因此 L1 miss。", "只有 L1 miss 后才查询 L2，本例命中。", "L2 返回包含目标字节的完整 64B 缓存行，而不是只返回一个字节。", "LRU 选中 way 1；它 valid=1、dirty=1，所以先写回旧块，再按 write-allocate 安装新块、执行写入并按 write-back 标脏。2.4ns 仅作为同帧性能指标。"],
  },
  40034: {
    kind: "pipeline",
    entities: [
      entity("virtual-address", "虚拟地址 v", "input", 13330), entity("page-size", "页大小 P", "input", 4096),
      entity("page-number", "页号 p", "intermediate", 0), entity("page-offset", "页内偏移 d", "intermediate", 0),
      entity("tlb-result", "首次 TLB 查询", "control", "unknown"), entity("pte-valid", "缺页前 PTE valid", "control", true, 1),
      entity("page-fault-event", "缺页异常", "control", "none", 1), entity("fault-state", "缺页处理状态", "control", "pending", 2),
      entity("resolved-frame", "页框 f(p)", "intermediate", "pending", 2), entity("pte-valid-after", "处理后 PTE valid", "control", false, 2),
      entity("permission", "访问权限", "control", "pending", 3), entity("tlb-entry", "填充的 TLB 表项", "intermediate", "pending", 4),
      entity("retry-result", "重试 TLB 查询", "control", "pending", 4), entity("physical-address", "物理地址 a", "output", "pending", 5),
    ],
    connections: [
      connection("va-page", "virtual-address", "page-number"), connection("va-offset", "virtual-address", "page-offset"), connection("page-tlb", "page-number", "tlb-result"),
      connection("tlb-pte", "tlb-result", "pte-valid"), connection("pte-fault", "pte-valid", "page-fault-event"), connection("event-handler", "page-fault-event", "fault-state"),
      connection("fault-frame", "fault-state", "resolved-frame"), connection("fault-valid", "fault-state", "pte-valid-after"),
      connection("frame-permission", "resolved-frame", "permission"), connection("valid-permission", "pte-valid-after", "permission"),
      connection("page-tlb-entry", "page-number", "tlb-entry"), connection("frame-tlb-entry", "resolved-frame", "tlb-entry"), connection("permission-tlb-entry", "permission", "tlb-entry"),
      connection("entry-retry", "tlb-entry", "retry-result"), connection("retry-address", "retry-result", "physical-address"),
      connection("frame-address", "resolved-frame", "physical-address"), connection("offset-address", "page-offset", "physical-address"),
    ],
    formulaBindings: { v: ["virtual-address"], P: ["page-size"], "p,d": ["page-number", "page-offset"], "f(p)": ["resolved-frame"], a: ["physical-address"] },
    frames: frames([
      { sources: ["virtual-address", "page-size"], targets: ["page-number", "page-offset", "tlb-result"], values: { "page-number": 3, "page-offset": 1042, "tlb-result": "miss" }, connections: ["va-page", "va-offset", "page-tlb"], transfers: [transfer("split-page", "virtual-address", "page-number", 13330, "提取页号"), transfer("split-offset", "virtual-address", "page-offset", 13330, "保留页内偏移"), transfer("lookup-tlb", "page-number", "tlb-result", 3, "用页号 3 查询 TLB")], result: "v=13330 拆为 p=3、d=1042；首次 TLB 查询 miss", check: check("tlb-result", "miss", "TLB 未命中"), checks: [check("page-number", 3, "虚拟页号为 3"), check("page-offset", 1042, "偏移为 1042") ] },
      { sources: ["tlb-result", "page-number"], targets: ["pte-valid", "page-fault-event"], values: { "pte-valid": false, "page-fault-event": "raised" }, connections: ["tlb-pte", "pte-fault"], transfers: [transfer("walk-pte", "tlb-result", "pte-valid", "miss", "TLB miss 后读取页表项"), transfer("raise-page-fault", "pte-valid", "page-fault-event", false, "PTE valid=0，触发缺页")], result: "页 3 的 PTE valid=0，CPU 触发 page fault", check: check("pte-valid", false, "缺页前有效位为 0"), checks: [check("page-fault-event", "raised", "缺页异常已触发") ] },
      { sources: ["page-fault-event", "pte-valid"], targets: ["fault-state", "resolved-frame", "pte-valid-after"], values: { "fault-state": "resolved", "resolved-frame": 7, "pte-valid-after": true }, connections: ["event-handler", "fault-frame", "fault-valid"], transfers: [transfer("enter-fault-handler", "page-fault-event", "fault-state", "raised", "进入缺页处理程序"), transfer("install-frame", "fault-state", "resolved-frame", "resolved", "调页到页框 7"), transfer("validate-pte", "fault-state", "pte-valid-after", "resolved", "把 PTE valid 更新为 1")], result: "缺页处理把页面装入页框 7，并将 PTE valid 更新为 1", check: check("fault-state", "resolved", "缺页处理完成"), checks: [check("resolved-frame", 7, "新映射指向页框 7"), check("pte-valid-after", true, "处理后页表项有效") ] },
      { sources: ["resolved-frame", "pte-valid-after"], targets: ["permission"], values: { permission: "allowed" }, connections: ["frame-permission", "valid-permission"], transfers: [transfer("frame-to-permission", "resolved-frame", "permission", 7, "检查页框 7 的访问权限"), transfer("valid-to-permission", "pte-valid-after", "permission", true, "仅检查有效 PTE 的权限")], result: "页框 7 的映射有效，且本次访问权限 allowed", check: check("permission", "allowed", "本次访问权限允许"), checks: [check("pte-valid-after", true, "权限检查基于有效 PTE") ] },
      { sources: ["page-number", "resolved-frame", "permission", "pte-valid-after"], targets: ["tlb-entry", "retry-result"], values: { "tlb-entry": "VPN 3 -> PFN 7, R/W allowed", "retry-result": "hit" }, connections: ["page-tlb-entry", "frame-tlb-entry", "permission-tlb-entry", "entry-retry"], transfers: [transfer("fill-tlb-vpn", "page-number", "tlb-entry", 3, "填充 VPN 3"), transfer("fill-tlb-pfn", "resolved-frame", "tlb-entry", 7, "填充 PFN 7"), transfer("fill-tlb-permission", "permission", "tlb-entry", "allowed", "填充允许权限"), transfer("retry-tlb", "tlb-entry", "retry-result", "VPN 3 -> PFN 7, R/W allowed", "重试页 3 的 TLB 查询")], result: "填充 VPN 3 -> PFN 7 后重试，TLB hit", check: check("retry-result", "hit", "重试命中 TLB"), checks: [check("tlb-entry", "VPN 3 -> PFN 7, R/W allowed", "TLB 表项来自处理后的映射") ] },
      { sources: ["resolved-frame", "page-size", "page-offset", "retry-result"], targets: ["physical-address"], values: { "physical-address": 29714 }, connections: ["frame-address", "offset-address", "retry-address"], transfers: [transfer("frame-to-address", "resolved-frame", "physical-address", 7, "使用重试得到的页框"), transfer("offset-to-address", "page-offset", "physical-address", 1042, "复用原偏移"), transfer("retry-to-address", "retry-result", "physical-address", "hit", "TLB 命中后允许拼接")], result: "a=7*4096+1042=29714", check: check("physical-address", 29714, "物理地址正确"), checks: [check("retry-result", "hit", "物理地址来自成功重试"), check("resolved-frame", 7, "重试使用页框 7"), check("page-offset", 1042, "转换前后偏移不变") ] },
    ]),
    explanations: ["虚拟地址先拆为页号 3 与偏移 1042；TLB 没有页 3 的缓存映射。", "TLB miss 后读取页表，PTE valid=0 才是本次 page fault 的直接原因。", "操作系统完成调页，把页框 7 写入 PTE 并将有效位置 1。", "对处理后的有效映射检查权限，本次读写访问被允许。", "把 VPN 3、PFN 7 和允许权限填入 TLB；重试同一访问后命中。", "成功重试得到页框 7，再与始终不变的偏移 1042 拼成物理地址 29714。"],
  },
  40035: {
    kind: "array",
    entities: [
      entity("branch-pc", "分支 PC", "input", 100), entity("table-index", "预测表索引", "intermediate", 0),
      entity("counter-before", "更新前计数器 s_t", "input", 1), entity("predicted-direction", "预测方向 y-hat", "intermediate", -1, 1),
      entity("speculative-pc", "推测下一 PC", "intermediate", 0, 2), entity("actual-direction", "真实方向 y_t", "intermediate", "pending", 3),
      entity("counter-after", "更新后计数器", "intermediate", 0, 4), entity("flushed-instructions", "冲刷指令数", "output", 0, 5),
      entity("correct-target", "正确目标 PC", "output", 0, 5), entity("event-index", "更新时序 t", "control", 7),
    ],
    connections: [connection("pc-index", "branch-pc", "table-index"), connection("counter-prediction", "counter-before", "predicted-direction"), connection("prediction-speculative", "predicted-direction", "speculative-pc"), connection("speculative-actual", "speculative-pc", "actual-direction"), connection("counter-update", "counter-before", "counter-after"), connection("actual-counter", "actual-direction", "counter-after"), connection("prediction-flush", "predicted-direction", "flushed-instructions"), connection("actual-flush", "actual-direction", "flushed-instructions"), connection("actual-target", "actual-direction", "correct-target")],
    formulaBindings: { s_t: ["counter-before"], "\\widehat{y}_t": ["predicted-direction"], y_t: ["actual-direction"], t: ["event-index"] },
    frames: frames([
      { sources: ["branch-pc", "event-index"], targets: ["table-index"], values: { "table-index": 5 }, connections: ["pc-index"], transfers: [transfer("index-predictor", "branch-pc", "table-index", 100, "提取 PC 低位")], result: "PC=100 索引表项 5", check: check("table-index", 5, "索引为 5") },
      { sources: ["counter-before", "table-index"], targets: ["predicted-direction"], values: { "predicted-direction": 0 }, connections: ["counter-prediction"], transfers: [transfer("read-counter", "counter-before", "predicted-direction", 1, "阈值比较 s<2")], result: "s_t=1，预测不跳转 y-hat=0", check: check("predicted-direction", 0, "预测方向明确可见") },
      { sources: ["predicted-direction", "branch-pc"], targets: ["speculative-pc"], values: { "speculative-pc": 104 }, connections: ["prediction-speculative"], transfers: [transfer("follow-prediction", "predicted-direction", "speculative-pc", 0, "沿顺序路径取指")], result: "按不跳转路径取 PC=104", check: check("speculative-pc", 104, "推测 PC 来自预测方向") },
      { sources: ["speculative-pc", "branch-pc"], targets: ["actual-direction"], values: { "actual-direction": 1 }, connections: ["speculative-actual"], transfers: [transfer("resolve-branch", "speculative-pc", "actual-direction", 104, "执行分支条件")], result: "执行后才揭示 y_t=1，发生误预测", check: check("actual-direction", 1, "真实方向为跳转") },
      { sources: ["counter-before", "actual-direction"], targets: ["counter-after"], values: { "counter-after": 2 }, connections: ["counter-update", "actual-counter"], transfers: [transfer("train-from-counter", "counter-before", "counter-after", 1, "读取旧计数器"), transfer("train-from-truth", "actual-direction", "counter-after", 1, "按真实跳转递增")], result: "计数器从 1 饱和更新到 2", check: check("counter-after", 2, "每次解析都训练计数器") },
      { sources: ["predicted-direction", "actual-direction", "speculative-pc"], targets: ["flushed-instructions", "correct-target"], values: { "flushed-instructions": 3, "correct-target": 400 }, connections: ["prediction-flush", "actual-flush", "actual-target"], transfers: [transfer("prediction-to-flush", "predicted-direction", "flushed-instructions", 0, "比较预测方向"), transfer("truth-to-flush", "actual-direction", "flushed-instructions", 1, "不一致触发冲刷")], result: "仅因 0!=1 冲刷 3 条并重定向到 400", check: check("flushed-instructions", 3, "误预测冲刷三条"), checks: [check("correct-target", 400, "重定向目标在解析后才可见"), check("predicted-direction", 0, "预测值仍可核对"), check("actual-direction", 1, "真实值仍可核对") ] },
    ]),
    explanations: ["先用分支 PC 索引预测表，此时真实方向和目标都隐藏。", "读取 s_t=1 后显式产生预测方向 0。", "前端据此沿顺序路径取 PC=104，仍未揭示真实结果。", "执行阶段才得到 y_t=1，从而确认误预测。", "真实结果训练两位计数器从 1 到 2。", "比较 0 与 1 后才冲刷 3 条错误路径并揭示正确目标 400。"],
  },
  40036: {
    kind: "array",
    entities: [
      entity("input-elements", "输入元素", "input", []),
      entity("parallel-fraction", "可并行比例 alpha", "input", 0), entity("serial-fraction", "串行比例 1-alpha", "input", 0.1),
      entity("simd-width", "SIMD 宽度", "input", 4), entity("simd-packets", "SIMD 分组", "intermediate", [], 1),
      entity("processor-count", "核心数 p", "input", 2), entity("core-assignments", "每核数据块", "intermediate", [], 2),
      entity("tail-mask", "每核尾向量掩码", "intermediate", [], 3), entity("core-0-sum", "核心 0 局部和", "intermediate", 0, 3),
      entity("core-1-sum", "核心 1 局部和", "intermediate", 0, 3), entity("final-sum", "最终归并和", "output", 0, 4),
      entity("speedup", "理论加速比 S(p)", "output", 1, 4),
    ],
    connections: [connection("input-simd", "input-elements", "simd-packets"), connection("input-cores", "input-elements", "core-assignments"), connection("assignments-mask", "core-assignments", "tail-mask"), connection("assignments-sum0", "core-assignments", "core-0-sum"), connection("assignments-sum1", "core-assignments", "core-1-sum"), connection("sum0-final", "core-0-sum", "final-sum"), connection("sum1-final", "core-1-sum", "final-sum"), connection("alpha-speedup", "parallel-fraction", "speedup"), connection("p-speedup", "processor-count", "speedup")],
    formulaBindings: { "\\alpha": ["parallel-fraction"], "1-\\alpha": ["serial-fraction"], p: ["processor-count"], "S(p)": ["speedup"] },
    frames: frames([
      { sources: ["input-elements", "parallel-fraction"], targets: ["input-elements", "parallel-fraction"], values: { "input-elements": [1, 2, 3, 4, 5, 6, 7, 8, 9, 10], "parallel-fraction": 0.9 }, result: "10 个元素可拆成独立读取", check: check("input-elements", [1, 2, 3, 4, 5, 6, 7, 8, 9, 10], "输入元素完整") },
      { sources: ["input-elements", "simd-width"], targets: ["simd-packets"], values: { "simd-packets": ["[1,2,3,4]", "[5,6,7,8]", "[9,10,_,_]"] }, connections: ["input-simd"], transfers: [transfer("pack-simd", "input-elements", "simd-packets", [1, 2, 3, 4, 5, 6, 7, 8, 9, 10], "按宽度 4 打包")], result: "形成两个满向量和一个尾向量", check: check("simd-packets", ["[1,2,3,4]", "[5,6,7,8]", "[9,10,_,_]"] , "SIMD 分组完整") },
      { sources: ["input-elements", "processor-count"], targets: ["core-assignments"], values: { "core-assignments": [[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]] }, connections: ["input-cores"], transfers: [transfer("split-cores", "input-elements", "core-assignments", [1, 2, 3, 4, 5, 6, 7, 8, 9, 10], "均分给两个核心")], result: "core 0=[1..5]，core 1=[6..10]，每核恰有 5 个元素", check: check("core-assignments", [[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]], "两个核心负载均为五个元素") },
      { sources: ["core-assignments", "simd-width"], targets: ["tail-mask", "core-0-sum", "core-1-sum"], values: { "tail-mask": [[true, false, false, false], [true, false, false, false]], "core-0-sum": 15, "core-1-sum": 40 }, connections: ["assignments-mask", "assignments-sum0", "assignments-sum1"], transfers: [transfer("mask-tail", "core-assignments", "tail-mask", [[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]], "各核 5 mod 4=1，尾向量各启用一个通道"), transfer("sum-core0", "core-assignments", "core-0-sum", [[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]], "核心 0 局部归约"), transfer("sum-core1", "core-assignments", "core-1-sum", [[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]], "核心 1 局部归约")], result: "每核尾向量掩码均为 1000；局部和分别为 15、40", check: check("tail-mask", [[true, false, false, false], [true, false, false, false]], "两个五元素分块各只剩一个有效尾通道") },
      { sources: ["core-0-sum", "core-1-sum", "parallel-fraction", "serial-fraction", "processor-count"], targets: ["final-sum", "speedup"], values: { "final-sum": 55, speedup: 1.818182 }, connections: ["sum0-final", "sum1-final", "alpha-speedup", "p-speedup"], transfers: [transfer("reduce-core0", "core-0-sum", "final-sum", 15, "归并核心 0"), transfer("reduce-core1", "core-1-sum", "final-sum", 40, "归并核心 1"), transfer("alpha-to-speedup", "parallel-fraction", "speedup", 0.9, "代入并行比例"), transfer("p-to-speedup", "processor-count", "speedup", 2, "代入核心数")], result: "15+40=55；Amdahl 加速比约 1.818", check: check("final-sum", 55, "并行结果等于标量基线"), checks: [check("core-0-sum", 15, "核心 0 局部和为 15"), check("core-1-sum", 40, "核心 1 局部和为 40"), check("speedup", 1.818182, "理论加速比约为 1.818", "approx") ] },
    ]),
    explanations: ["先确认十个输入元素可独立读取，局部和与最终结果尚不揭示。", "若单核连续处理全部输入，SIMD 宽度 4 会形成两个满向量和一个双通道尾向量。", "分给两个核心后，每核各有五个元素；尾掩码必须在每个局部分块内重新计算。", "每核先处理一个四通道满向量，再以 1000 掩码处理自己的单元素尾向量，得到局部和 15、40。", "同步点归并得到 55，同时由 alpha=0.9、p=2 得到受串行部分限制的理论加速比。"],
  },
} satisfies ConceptSceneProfileTable;
